### PR TITLE
Conversion of precompiled mode to built-in patch

### PR DESCRIPTION
**Pull request by taoenwen**
[1] Remove precompiled instruction (HACK_SOUND)
[2] Change to built-in patch
image
image
[3] Built-in patch added switch
image
[4] Built-in patch added flag (BDF_BUILTIN)
image

### CODE REVIEW

**Comment by barbudreadmon** [comment]
Hmm i'd rather have this choice as a dipswitch for the concerned games ?

**Comment by taoenwen** [comment]
@barbudreadmon
Your suggestion is very good, I will modify them.

**Comment by barbudreadmon** [comment]
>Dipswitch can't seem to control them

I can look into this if you don't manage to find a solution

**Comment by taoenwen** [comment]
I temporarily removed the code base.

**Comment by taoenwen** [comment]
@barbudreadmon 
Give me some time, I can finish them.

**Pull request closed without merging**
