### PR TITLE
latest mame v60 updates

### PR DESCRIPTION
**Pull request by grant2258**
some updates from the mame team a few days ago

### CODE REVIEW

**Comment by Loggan08** [comment]
m_modwritevalh - undeclared identifier

**Comment by barbudreadmon** [comment]
You might also consider backporting https://github.com/mamedev/mame/commit/6b3a98637c513a38515236790f48f63b32e72cef#diff-95656de9095a0a392bba4c69906417b6 and https://github.com/mamedev/mame/commit/e9c63ab61cb244e98e23c7c17e3e0f45f087bedb#diff-95656de9095a0a392bba4c69906417b6

**Comment by grant2258** [comment]
> 
> 
> You might also consider backporting [mamedev/mame@6b3a986#diff-95656de9095a0a392bba4c69906417b6](https://github.com/mamedev/mame/commit/6b3a98637c513a38515236790f48f63b32e72cef#diff-95656de9095a0a392bba4c69906417b6) and [mamedev/mame@e9c63ab#diff-95656de9095a0a392bba4c69906417b6](https://github.com/mamedev/mame/commit/e9c63ab61cb244e98e23c7c17e3e0f45f087bedb#diff-95656de9095a0a392bba4c69906417b6)

do we use the disassembler on this port?

**Comment by Loggan08** [comment]
with backporting I'm guessing that the static-cast to be converted to C-Style.

**Comment by Loggan08** [comment]
errors about driver : Nkdodgeb

**Comment by grant2258** [comment]
what errors loggan ?

**Comment by Loggan08** [comment]
@grant2258 

The appveyor-build did.

**Comment by grant2258** [comment]
I dont think that is related to this at all could be wrong
```
burn.obj : error LNK2001: unresolved external symbol "struct BurnDriver BurnDrvNkdodgeb" (?BurnDrvNkdodgeb@@3UBurnDriver@@A) [C:\projects\fbneo-kbhgd\projectfiles\visualstudio-2019\fba_vs2010.vcxproj]
burn.obj : error LNK2001: unresolved external symbol "struct BurnDriver BurnDrvNkdodge" (?BurnDrvNkdodge@@3UBurnDriver@@A) [C:\projects\fbneo-kbhgd\projectfiles\visualstudio-2019\fba_vs2010.vcxproj]
burn.obj : error LNK2001: unresolved external symbol "struct BurnDriver BurnDrvSpdodgeb" (?BurnDrvSpdodgeb@@3UBurnDriver@@A) [C:\projects\fbneo-kbhgd\projectfiles\visualstudio-2019\fba_vs2010.vcxproj]
C:\projects\fbneo-kbhgd\projectfiles\visualstudio-2019\Win32\Release\fbneo_vs.exe : fatal error LNK1120: 3 unresolved externals [C:\projects\fbneo-kbhgd\projectfiles\visualstudio-2019\fba_vs2010.vcxproj]
```

**Comment by Loggan08** [comment]
I just think the .cpp files have to be added to the vcxproj

**Comment by grant2258** [comment]
yea looks like src/burn/drv/pre90s/d_spdodgeb.cpp is missing

**Comment by Loggan08** [comment]
@grant2258 

My windows "patch" has that, just check the diff.
Also check out the .filters file.

**Comment by grant2258** [comment]
I dont have vs am using msys and linux i looked here https://github.com/finalburnneo/FBNeo/blob/master/projectfiles/visualstudio-2019/fba_vs2010.vcxproj.filters. I am assuming this is the right place.  I dont see the d_spdodgeb.cpp there at all

**Comment by Loggan08** [comment]
these two

https://github.com/Loggan08/FBNeo/blob/master/projectfiles/visualstudio-2019/fba_vs2010.vcxproj
https://github.com/Loggan08/FBNeo/blob/master/projectfiles/visualstudio-2019/fba_vs2010.vcxproj.filters

**Comment by grant2258** [comment]
ah got you now will be fixed when its pulled sorry im not familiar with appveyorappveyor it a handy thing though

**Comment by barbudreadmon** [comment]
@grant2258 you are right, i thought v60d was being used one way or another in fbneo but it doesn't

**Comment by Loggan08** [comment]
changes been merged (as another commit)

Close commit ?

**Comment by grant2258** [comment]
yea no piont in leaving it open :)

**Pull request closed without merging**
