### PR TITLE
Trying to fix sdl compilation

### PR DESCRIPTION
**Pull request by taoenwen**

### CODE REVIEW

**Comment by taoenwen** [comment]
@barbudreadmon I'm very new to sdl, can you check this for me so that it is not troubleshooting

**Comment by barbudreadmon** [comment]
you need to make that unicode stuff entirely optional/disabled for platforms that don't support unicode

**Comment by barbudreadmon** [comment]
probably gonna be ok with https://github.com/finalburnneo/FBNeo/commit/528d345a85263a11dd79f35496e496a57cf1bb03

**Comment by taoenwen** [comment]
@barbudreadmon Thank you for your assistance.

**Comment by barbudreadmon** [comment]
It was built successfully, i'll close.
If the `UINT32` to `INT32` change was somehow required for a reason unrelated to those sdl build failures, please make a separate PR.

**Comment by taoenwen** [comment]
> 
@barbudreadmon i There is the possibility of a prejudgemental rejection, so next time I will change it to INT32, currently there will be almost no problems, thanks again for your assistance and reminder.

**Pull request closed without merging**
