### PR TITLE
update hack games & to LF

### PR DESCRIPTION
**Pull request by taoenwen**
d_cps1: wofdr20/kodsr/wofhfh & dinohunt scenario
d_cps2: hsf2df/xmvsfem/mvscem/mshvsfem/hsf2ev2/hsf230b
d_neogeo: mslug5bs/mslug3cq/mslug3fs/wh2es/wh2jes/ssho2emb/ffurspbt/ffury2es/ffury3eh/mslug5cq/lastblad mini game (aes mode)
d_pwrinst2: plegendsjq/to LF
d_m92: nbbatmbh/hookpls/nbbat1v2/nbbat1v4/nbbat1v8/nbbatmx2/hookbo/hooknx2/hookpj/hooksw/hookx2/hookxr/hookxx/hookgs/hookgs2/hookhd/hookhd2/hookjy/hooknx/hook1v4/hook6h/hookdszz/hookdw
d_pgm: kovshszl/kovshxsh/kovshmg/kovshdf/killbldqy/killbldjq
pgm_run: fix for kovsh & hacks a0613 rom overlap/to LF

test: https://drive.google.com/drive/folders/1qqk2cNlE5ecb6wMGjJmAqTef2xVgshyJ?usp=drive_link

### CODE REVIEW

**Comment by dangonzilla** [comment]
Hi @taoenwen, I've reviewed the new kodsr hack update and you forgot to change the CRC from these lines so it fully becomes the USA 910910 revision :

// The King of Dragons (Remix Special, Hack)
// Modified by Bonusjz

{ "kd_09.12a",     0x010000, 0xbac6ec26, BRF_PRG | CPS1_Z80_PROGRAM },

{ "kd_18.11c",     0x020000, 0x4c63181d, BRF_SND | CPS1_OKIM6295_SAMPLES },
{ "kd_19.12c",     0x020000, 0x92941b80, BRF_SND | CPS1_OKIM6295_SAMPLES },

I tell you this information in case it can be fixed before they publish the updated hack on FBNeo.
Thank you very much.
Daniel.

**Comment by taoenwen** [comment]
> I tell you this information in case it can be fixed before they publish the updated hack on FBNeo. 

Thanks!

**Comment by dinkc64** [comment]
@taoenwen, I invite you to have direct access to the repo, this way you can merge your PR's or just push directly

**Comment by cIymax** [comment]
Just wanted to document that support for the following hack was also added.

d_cps2: ssf2tdf

Was actually in the middle of working on a PR myself to add hsf2df and ssf2tdf before I saw they've already been added.

**Pull request merged**
