### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by alifare**

### CODE REVIEW

**Review by alifare — COMMENTED** [review]
Added support code for kof97pm.zip

**Comment by dinkc64** [comment]
Hi, 
It looks like something went wrong here - can you please re-do the pull request with only your changes added to d_neogeo.cpp?  Thanks :)

best regards,
- dink

**Comment by alifare** [comment]
> Hi,
> It looks like something went wrong here - can you please re-do the pull request with only your changes added to d_neogeo.cpp? Thanks :)
> 
> best regards,
> 
> * dink

Sorry, I am not familiar with the operations. How can I do that?

**Comment by dinkc64** [comment]
Here's a little documentation: https://opensource.com/article/19/7/create-pull-request-github

or search on google: github how to make a pull request :)

best regards,
- dink

**Pull request closed without merging**
