### PR TITLE
Add ARM946ES and ATMEL_ARM_AIC to prepare for PGM2

### PR DESCRIPTION
**Pull request by eziochiu**

### CODE REVIEW

**Comment by barbudreadmon** [comment]
Thanks for your contribution !

Is anything in this PR a backport from someone's work ? It's important to mention it in the headers.

At the very least, it seems atmel_arm_aic.cpp might be a backport of [this](https://github.com/mamedev/mame/blob/master/src/devices/machine/atmel_arm_aic.cpp), so it probably needs 
```
// license:BSD-3-Clause
// copyright-holders:David Haywood, MetalliC
```

**Comment by eziochiu** [comment]
> Thanks for your contribution !
> 
> Is anything in this PR a backport from someone's work ? It's important to mention it in the headers.
> 
> At the very least, it seems atmel_arm_aic.cpp might be a backport of [this](https://github.com/mamedev/mame/blob/master/src/devices/machine/atmel_arm_aic.cpp), so it probably needs
> 
> ```
> // license:BSD-3-Clause
> // copyright-holders:David Haywood, MetalliC
> ```

Alright, I will add them.

**Comment by barbudreadmon** [comment]
I'm also noticing `OldCodeMode` is removed in this PR.
I might be wrong but i think it's a workaround to reproduce "old emulation bugs" which are necessary to support some "old romhacks". I'll flag @taoenwen about this.

**Comment by eziochiu** [comment]
> I'm also noticing `OldCodeMode` is removed in this PR. I might be wrong but i think it's a workaround to reproduce "old emulation bugs" which are necessary to support some "old romhacks". I'll flag @taoenwen about this.

What does "old emulation bugs" refer to?

**Comment by eziochiu** [comment]
> I'm also noticing `OldCodeMode` is removed in this PR. I might be wrong but i think it's a workaround to reproduce "old emulation bugs" which are necessary to support some "old romhacks". I'll flag @taoenwen about this.

Maybe it's just for compatibility with old hack games, but is it really necessary?

**Comment by barbudreadmon** [comment]
I'm not knowledgeable enough about this `OldCodeMode` stuff, i'll leave the answer to the experts :)

**Comment by eziochiu** [comment]
> I'm not knowledgeable enough about this `OldCodeMode` stuff, i'll leave the answer to the experts :)

Alright, no worries. If the code still works, I'll add it back.

**Comment by dinkc64** [comment]
Hi, this oldcodemode stuff is needed for the hack games to work.  Here is the story:
Over the past 20 years ago since PGM was emulated in fbn and mame, people made dozens of hack games.
A few years ago, iq_132 made several improvements to make the PGM emulation more like real HW.  This removed some ficticious memorychunks and other things that aren't available on real PGM hw..  (he has PGM hw and made many, many tests).
The hack games, which were made in emulator-times, all rely on the old emulation, which includes the ficticious memory. They stopped working..
Maybe @taoenwen will explain better?

best regards,
- dink

**Comment by eziochiu** [comment]
> Hi, this oldcodemode stuff is needed for the hack games to work. Here is the story: Over the past 20 years ago since PGM was emulated in fbn and mame, people made dozens of hack games. A few years ago, iq_132 made several improvements to make the PGM emulation more like real HW. This removed some ficticious memorychunks and other things that aren't available on real PGM hw.. (he has PGM hw and made many, many tests). The hack games, which were made in emulator-times, all rely on the old emulation, which includes the ficticious memory. They stopped working.. Maybe @taoenwen will explain better?
> 
> best regards,
> 
> * dink

I rolled back the PGM code.

**Comment by taoenwen** [comment]
Let's take a look at the results of progress; moving forward has always been a necessity.

**Comment by eziochiu** [comment]
The code has some bugs, so I will close this PR.

**Comment by eziochiu** [comment]
When I decrypted KOV2NL, some errors occurred, and it's a bit different from my original code.I will check later.

**Comment by barbudreadmon** [comment]
Is it ready for merge ?

**Comment by eziochiu** [comment]
image
Although there are still many issues, it at least proves that it can still run.

**Comment by eziochiu** [comment]
> Is it ready for merge ?

Sorry Brabu, I have run out of patience. I have closed this PR. If possible, please delete it.

**Comment by barbudreadmon** [comment]
Hmmm what was the issue ? Maybe we could help ?

**Comment by eziochiu** [comment]
> Hmmm what was the issue ? Maybe we could help ?

I'm not sure. In my original code, ARM9 was written together with ARM7, but in the submitted code, I separated this part and submitted it individually.

**Comment by dinkc64** [comment]
If don't feel like separating it, then don't :)
Work in the best way possible for you, we can always help sort things out at later time.

**Comment by taoenwen** [comment]
@eziochiu As we've talked about privately, just do it the way you're used to, e.g., remove OldCodeMode first, and add more if necessary.

**Comment by eziochiu** [comment]
> @eziochiu As we've talked about privately, just do it the way you're used to, e.g., remove OldCodeMode first, and add more if necessary.

No, it's not that issue; it's the ARM9 code.

**Pull request closed without merging**
