### PR TITLE
update dat creation

### PR DESCRIPTION
**Pull request by grant2258**
We cant use the all in one system dat because of name conflicts so make all the dats that are available.

### CODE REVIEW

**Comment by grant2258** [comment]
Just a little update I fixed the global datfile creation for sdl2 only. I know libretro uses the subsystem to do this. so the for example the aburner rom had a conflict with the arcade rom. When i took away the lead removal it lets us call the game at the command prompt with ./fbneo spec_aburner. Im not sure why the lead was removed but im sure there is good reasons just to let you know its only the sdl2 port this will change on perhaps the sdl1 port as well.

**Comment by grant2258** [comment]
Seems this is good for building the global dat will need to dig a little more to launch the roms with the names so dont pull yet till. The gui is listing the roms with these names as well must be changing it somewhere else as well.

**Comment by tmaul** [comment]
Yeah, the prefixes are filtered out, they are just there so it doesn't screw up the internal gamelist. They see filtered out when loading, with the assumption that each system has its own room folder to avoid .zip name clashes

**Comment by grant2258** [comment]
its not really a big deal to be honest can use different folder. I like everything in one directory might just make this updated for myself will see what i end up with and you guys can make the choice if you want it or not for the sdl build for now ill just change this so it creates all the dats with no functionality changes.

**Comment by grant2258** [comment]
Ok changed it to just create the dats for all the systems.  for both sdl versions the global isint usable at the moment

**Comment by grant2258** [comment]
closing this one and opening a new one.

**Pull request closed without merging**
