### PR TITLE
fix build problems under mamemingw when using multithreading

### PR DESCRIPTION
**Pull request by systempal**

### CODE REVIEW

**Comment by dinkc64** [comment]
thanks!

**Comment by systempal** [comment]
I saw the commit was partially reverted/corrected right ?

**Comment by dinkc64** [comment]
What do you mean?  I merged it exactly how you wrote the pr

**Comment by systempal** [comment]
i think i've some problem under my pc ;)

**Comment by taoenwen** [comment]
> i think i've some problem under my pc ;)

@systempal Hi,

Please submit the correct changes as soon as possible, this may affect user compilation and generation, thank you!

**Comment by systempal** [comment]
looks googd actually, its only me! I did not sleep!

**Comment by dinkc64** [comment]
no problem, happens to the best of us :)

**Comment by barbudreadmon** [comment]
Does it fix the bug where the build would randomly fail when adding `-j<number>` to the make command ?

**Comment by systempal** [comment]
Yes,
can you confirm =

**Pull request merged**
