### PR TITLE
d_supduck.cpp - Big Endian fix

### PR DESCRIPTION
**Pull request by crystalct**

### CODE REVIEW

**Comment by crystalct** [comment]
@barbudreadmon @dinkc64 
I'm tiring to endianize d_supernova.cpp but it's a bit hard...
I have already fixed a couple of thing in sh2.cpp  (`RL(UINT32 A)` and `WL(UINT32 A, UINT32 V)`) and sknsspr.cpp.
there is the call to DrvScan that i dont understand....
A pice of output:
(PS3)
```
VblokbrkInit
Sh2Reset - pc: 0x430 - r15: 0xc0000800
sh2->pc: 0x430 - sh2->r[15]: 0xc0000800 - sh2->sr: 0xf0
DrvScan action: 0x78
ACB_MEMORY_RAM
ACB_DRIVER_DATA
ACB_NVRAM
suprnova_speedhack - a: 0x6027cb8 - pc: 0x430 b: 0x6027cb8 - speedhack_address: 0xffffffff
suprnova_write_byte - address:0x0 - data: 0x0 x4
suprnova_write_byte - address:0x4 - data: 0x0
suprnova_write_byte - address:0x0 - data: 0x0 x3
```
(X86)
```
VblokbrkInit
Sh2Reset - pc: 0x430 - r15: 0xc0000800
sh2->pc: 0x430 - sh2->r[15]: 0xc0000800 - sh2->sr: 0xf0
DrvScan action: 0x78
ACB_MEMORY_RAM
ACB_DRIVER_DATA
ACB_NVRAM
DrvScan action: 0x8
ACB_NVRAM
DrvScan action: 0xa
ACB_NVRAM
ACB_WRITE
suprnova_write_byte - address:0x2040000e - data: 0x0
suprnova_write_byte - address:0xc00000 - data: 0x80
suprnova_write_byte - address:0xc00001 - data: 0x88
suprnova_write_byte - address:0xc00000 - data: 0x81
suprnova_write_byte - address:0xc00001 - data: 0x0
suprnova_write_byte - address:0xc00000 - data: 0xff
```
On X86 is called 3 times... once on PS3.... any advice?

**Comment by barbudreadmon** [comment]
2 pieces of warnings about sh2 based games : 
- i believe the cps3/sh2 BE hacks were done in a non-standard way (i don't know why, might be to save performance since cps3 is probably borderline for those BE machines), meaning you might have to fix cps3 after making any change to sh2, or maybe even consider rewriting those cps3/sh2 hacks from scratch.
- suprnova probably won't run fullspeed on ps3, iirc it was running half speed on rpi3.

**Comment by crystalct** [comment]
It seems sh2 changes aren't necessary and it seems 
```
BurnSwapEndian(DrvSh2BIOS, 0x80000);
BurnSwapEndian(DrvSh2ROM, 0x200000);
```
must be:
```
#ifdef LSB_FIRST
		BurnSwapEndian(DrvSh2BIOS, 0x80000);
		BurnSwapEndian(DrvSh2ROM, 0x200000);
#endif
```

**Comment by dinkc64** [comment]
so, you got it then? :)

**Comment by crystalct** [comment]
no... a little closer

**Pull request merged**
