### PR TITLE
d_megadrive: md_megamanfix

### PR DESCRIPTION
**Pull request by Igor-Arabe**
Added correct crc32, romname.

base: megamanrb rom + (U-RB)-v105 ips

I believe the original intention was add jp-rom and megamanrb with  "fixer upper" patch. if this isn't correct let me know.

### CODE REVIEW

**Comment by Igor-Arabe** [comment]
Now is ok.

**Comment by dinkc64** [comment]
I think gab75 has updated this already, but not sure ?

**Comment by Igor-Arabe** [comment]
Not completely. He added megamanfix with crc and romname like as on megamanrb.

check commit: https://github.com/finalburnneo/FBNeo/commit/6ce192221edc106a327d3ce72f7165359bb77a4c

**Comment by dinkc64** [comment]
oh, I see - thanks!

**Pull request merged**
