### PR TITLE
update ips function & others

### PR DESCRIPTION
**Pull request by taoenwen**
[1] Add some ips macros
[2] Adjust ips logic for neogeo/cps-1
[3] Simplified loading and mapping of neogeo's Extra Rom
[4] Standardize naming of rom labels in some neogeo hack sets
[5] Enable extra rom in neogeo hack ips
[6] wofjdr update to 20220603

### CODE REVIEW

**Comment by taoenwen** [comment]
test : Enable extra rom in neogeo hack ips
[fbneo.zip](https://github.com/finalburnneo/FBNeo/files/8864076/fbneo.zip)

test : sets
https://drive.google.com/drive/folders/1qqk2cNlE5ecb6wMGjJmAqTef2xVgshyJ?usp=sharing

**Comment by dinkc64** [comment]
taoenwen, nice work! :)

**Comment by dinkc64** [comment]
@taoenwen, I received pm from alicemsu, wanted to know if we will add their neogeo hacks from gotvg, and to put name on hacks we already have by them ("alicemsu, chamcham425" in Released: field, instead of "hack")
https://archive.org/download/Fightcade2RomsMetalSlug
https://ia902305.us.archive.org/25/items/Fightcade2RomsMetalSlug/RomName.txt
I modify romname.txt and add !!! to roms we don't have yet:
[RomName.txt](https://github.com/finalburnneo/FBNeo/files/8867086/RomName.txt)

Would you help? :)

best regards,
- dink

**Comment by taoenwen** [comment]
OK, I'll check it out after work

**Pull request merged**
