### PR TITLE
Update version.h

### PR DESCRIPTION
**Pull request by tmaul**
In preperation for v1.0.0.0....

Please update whatsnew, readmes, etc as needed, and once we are happy we will merge this and that will be v1.0.0.0 :)

### CODE REVIEW

**Comment by dinkc64** [comment]
sounds good :)

**Comment by JacKc029735** [comment]
yeah sounds good :)

**Comment by barbudreadmon** [comment]
Sounds good and @iq132 agreed too.
Let's merge this saturday ?

**Comment by tmaul** [comment]
Can we do it Friday night or Sunday maybe? I was going to repackage the autobuild from the merge and upload that as the release to the main rep but I'm not about on Saturday. Although I'm totally cool with someone else doing the release instead 🙂

**Comment by barbudreadmon** [comment]
> Can we do it Friday night or Sunday maybe?

Sure :)

**Comment by dinkc64** [comment]
Hey guys, we should probably add a Highlights section at the top of the whatsnew with the best new stuff, and, of course, update the whatsnew and stuff.  I also wanted to update the docs but havn't had the time, I think this weekend is too soon, would you guys be ok with next weekend?

**Comment by dinkc64** [comment]
I'd also like to finish the de-barrification[improvements] of the spectrum driver for the release...

**Comment by barbudreadmon** [comment]
No problem, i didn't know you had any set goal :)
Not sure what stuff we should put in the highlights section ? Major rewrites ? New drivers ? Long-time issues fixed ?

**Comment by tmaul** [comment]
That sounds good to me, no point in releasing if it's not quite where it needs to be

**Comment by JacKc029735** [comment]
Let's wait until all spectrum stuff is done...but i hope it will be not too long :)

**Comment by LodanZark** [comment]
Will the fba.chm file be edited or will be ditched in the final version?

**Comment by barbudreadmon** [comment]
Since i believe @dinkc64 isn't done with spectrum, for now maybe we should wait for mame 0.226 and our syncing with their set to make things easier for users ? It should happen very soon since they basically do one release per month.

**Comment by dinkc64** [comment]
I'm making very good progress with spectrum, but it seems like each "issue" that I work on takes about 3-4 days a piece.  there are 2.5 left.  For the release, I really don't want the spectrum driver to be "the heap of steaming shit parting gift that barry left us", as it was since he added it.

**Comment by mobasuite** [comment]
MAME 226 should be done before the end of the month from what I've heard, a sync would be nice.

**Comment by dinkc64** [comment]
kev :)

**Comment by dinkc64** [comment]
@barbudreadmon 
Please link the windows XP binary in the release page :)

**Comment by dinkc64** [comment]
@barbudreadmon, @tmaul 
any chance someone could remove the ghosted entries from the whatsnew.html file in the release zips?
3 under "Added analog support in ghox"
and 6 under "Added driver for ZX Spectrum based games" ?

**Comment by tmaul** [comment]
@dinkc64  Done :)

**Comment by dinkc64** [comment]
@tmaul thanks!
excellent work guys :)

**Pull request merged**
