### PR TITLE
CPS1 games (No sound) with QSound [Hack]

### PR DESCRIPTION
**Pull request by taoenwen**
Precompiled instructions are off by default.
Enable by HACK_SOUND=1

### CODE REVIEW

**Comment by barbudreadmon** [comment]
It only affects hacks ?
Why would we want this disabled ? Those hacks have no sound otherwise, right ?

**Comment by taoenwen** [comment]
For some "No Sound" cps1 games, Get QSound by means of [rom hack],
It only branches in the compile switch selection and doesn't change anything,
The default off is to not affect the real simulation.

**Comment by dinkc64** [comment]
taoenwen, nice! :)

**Comment by barbudreadmon** [comment]
>The default off is to not affect the real simulation.

Hmmm, if there is some interest in having both "simulation" and "qsound version", maybe it could be turned into something that can be chosen at runtime through some dips ?

**Comment by taoenwen** [comment]
@barbudreadmon 
This means that two sound systems must be included,
May cause confusion between [play] and [simulation] ...

**Comment by dinkc64** [comment]
taoenwen, is it ready for merge?

**Comment by taoenwen** [comment]
Yes, it's ready.

**Pull request merged**
