### PR TITLE
romhacks update

### PR DESCRIPTION
**Pull request by lolsuite**
requested changes

### CODE REVIEW

**Comment by Igor-Arabe** [comment]
Make some changes in...
Line 30155: add date from changelog, this hack don't have versions number.
Change to: Final Fantasy VI Reimagined (Hack) - 2024-10-30

Line 30527: need to change _gameName_ too.
correct is: **Legend of Zelda, The - 18 Hours Past (Hack, v1.12)**

**Comment by lolsuite** [comment]
btw @Igor-Arabe do you happen to have the CRC of the frameratehack 1.4 roms ?

**Comment by SoulReeverUK** [comment]
Hi there.

I requested this on the Neo-Source forums. The correct order is frame-rate patch first then the English patch (according to readme.txt from frame-rate IPS patch). Here's the details for the 4 updates I requested:

Final Fantasy VI Reimagined (2024-10-30)(DrakeyC).sfc - 60AFF03D - 4,194,304
Legend of Zelda, The - 18 Hours Past v1.12 (2024)(Letterbomb).sfc - C2DC7B83 - 2,097,152
Ranma 1-2 - Chougi Ranbu Hen frameratehack v1.4 (2024)(Upsilandre).sfc - 1705415F - 4,194,304
Ranma 1-2 - Hard Battle II - Super Move Hustle T-Eng + frameratehack v1.4 (2024)(Upsilandre).sfc - 22AE0893 - 4,194,304

**Comment by dinkc64** [comment]
Since this pr is messy, I wont merge it until the author says they're done with whatever it is they're trying to do.

best regards,
- dink

**Comment by dinkc64** [comment]
SoulReever, I think gab75 is taking a break.  Working on this snes really wore us (me and gab75) down, .. it was a lot of work!
So feel free to make a pr with any additions / changes you want.

best regards,
- dink

**Comment by lolsuite** [comment]
I understand working on the snes core must have been hard work. I will update the framerate hacks crcs then call it quits.

**Comment by SoulReeverUK** [comment]
Hi dink,

Completely understand and appreciate all the work you and gab75 have done on adding this core to FBN. My additions requested on the forums can wait. :)

I'll leave lolsuite to update this PR with the CRC values from my previous message for the changes they want to pull - which I believe has already be done just now.

**Comment by dinkc64** [comment]
lolsuite you should probably remove d_snes from vc project file, its missing all the rest of the stuff to make it work.

**Comment by lolsuite** [comment]
well you should add it internally then because it's impossible to edit it otherwise.

**Pull request closed without merging**
