### PR TITLE
win32 : separate names for subgames

### PR DESCRIPTION
**Pull request by taoenwen**
- d_neogeo : hack games update to latest
- add ShortNameA for all subgames
- add subgame gamelistex language glt support (requires loading basic gamelist)

test :
https://drive.google.com/drive/folders/1qqk2cNlE5ecb6wMGjJmAqTef2xVgshyJ?usp=sharing

gamelistex test:
[gamelist.zip](https://github.com/finalburnneo/FBNeo/files/11802372/gamelist.zip)

### CODE REVIEW

**Comment by taoenwen** [comment]
add FullNameA for all subgames, not ShortNameA

**Comment by barbudreadmon** [comment]
I have mixed feelings about new burn.cpp variables being used that way in game drivers. Couldn't it be done mostly in burn.cpp's BurnDrvInit/BurnDrvExit ?

**Comment by taoenwen** [comment]
@barbudreadmon You mentioned this suggestion, I will readjust it after I finish work today，thanks

**Comment by taoenwen** [comment]
@barbudreadmon 
- Some processes moved upstream;
- The nBurnDrvSubActive variable is used to get the subgame token and then find the corresponding FullNameW in gamelistex, so it has to exist;

**Comment by taoenwen** [comment]
fixed
image

**Comment by dinkc64** [comment]
@taoenwen, hi - is this ready for merge? 

best regards,
- dink

**Comment by taoenwen** [comment]
@dinkc64 Yes, it's ready,Thanks!

**Pull request merged**
