### PR TITLE
Neo Geo Additional Hacks

### PR DESCRIPTION
**Pull request by WandeingLagomorph793**
Adjusted some formatting and took out Fatal Fury 2's hack in case that was causing errors.

### CODE REVIEW

**Comment by barbudreadmon** [comment]
Please don't send PR anymore, or change method to do them ('add files via upload" is obviously a crappy method), all of the PR you send have the same issue.

**Comment by WandeingLagomorph793** [comment]
Alright. I recall doing these exact steps last time and they worked so I'm still trying to adjust and figure out what's going wrong. It looked like I was getting close on this one, I'm trying to make sure it's formatted as it should while looking back at what worked before, maybe it's just how it's being uploaded.

**Comment by barbudreadmon** [comment]
Maybe, tbh i only use command-line git so i don't know how "adding files via upload" works

**Comment by WandeingLagomorph793** [comment]
I've just tried doing that and noticed the additions numbering at +574 rather than the +20,000 it was the last few times, I'm thinking it was trying to put the d_neogeo.cpp file in the main folder directory, not the /src/burn/drv/neogeo folder that it's supposed to go into, so it might have had build issues with that I'm thinking.

 I just tried on my own with actions enabled and it seemed to build correctly when I tried the new method, like manually going into the folder and going from there, though I'm uncertain of any discrepancies between those actions compared to how the Appveyor builds it. 

I also double checked the formatting to make sure I didn't miss something in the file itself that could break it, comparing these to the ones from last time like Real Bout 2.

**Pull request closed without merging**
