### PR TITLE
Street Fighter III HBMame

### PR DESCRIPTION
**Pull request by MavisCelus19201**
sourced from hbmame.

### CODE REVIEW

**Comment by barbudreadmon** [comment]
i see several errors in this commit, so i don't think you tested it

**Comment by MavisCelus19201** [comment]
any specific ones? looked through with two code editors plus githubs preview to make sure the format was correct but not sure if i missed something. might have to do with the spacing im figuring.

**Comment by barbudreadmon** [comment]
it wasn't about spacing, and there were errors everywhere, please use a build environment to check that FBNeo build and the new games work.

**Comment by MavisCelus19201** [comment]
> it wasn't about spacing, and there were errors everywhere, please use a build environment to check that FBNeo build and the new games work.

dumb question but were the errors from the checksums themselves or the formatting? i want to make sure i'm fixing the right things and see what the best way to go about it is.

**Comment by grant2258** [comment]
you missed one quote a few commas and a driver one declaration has too many parameters. I dont have the rom to test if its working or not though. 

```
diff --git a/src/burn/drv/cps3/d_cps3.cpp b/src/burn/drv/cps3/d_cps3.cpp
index b6651772e..673ec123d 100644
--- a/src/burn/drv/cps3/d_cps3.cpp
+++ b/src/burn/drv/cps3/d_cps3.cpp
@@ -2085,9 +2085,9 @@ static struct BurnRomInfo sfiii3bhRomDesc[] = {
 	{ "sfiii3-simm6.3",					0x200000, 0x1a990249, BRF_GRA },
 	{ "sfiii3-simm6.4",					0x200000, 0x20cb39ac, BRF_GRA },
 	{ "sfiii3-simm6.5",					0x200000, 0x5f844b2f, BRF_GRA },
-  { "sfiii3-simm6.6",					0x200000, 0x450e8d28, BRF_GRA },
-	{ "sfiii3-simm6.7",					0x200000, 0xcc5f4187, BRF_GRA }
-	{ "sfiii3-simm6.7",					0x200000, 0xcc5f4187, BRF_GRA }
+	{ "sfiii3-simm6.6",					0x200000, 0x450e8d28, BRF_GRA },
+	{ "sfiii3-simm6.7",					0x200000, 0xcc5f4187, BRF_GRA },
+	{ "sfiii3-simm6.7",					0x200000, 0xcc5f4187, BRF_GRA },
 	{ "10bh",					0x200000, 0xb18be430, BRF_GRA },
 	{ "20",					0x200000, 0x5ca8faba, BRF_GRA },
 	{ "30",					0x200000, 0xb37cf960, BRF_GRA },
@@ -2095,8 +2095,8 @@ static struct BurnRomInfo sfiii3bhRomDesc[] = {
 	{ "40",					0x200000, 0x632c965f, BRF_GRA },
 	{ "41",					0x200000, 0x7a4c5f33, BRF_GRA },
 	{ "50",					0x200000, 0x8562358e, BRF_GRA },
-	{ "51",					0x200000, 0x7baf234b, BRF_GRA }
-	{ "60",					0x200000, 0xbc9487b7, BRF_GRA }
+	{ "51",					0x200000, 0x7baf234b, BRF_GRA },
+	{ "60",					0x200000, 0xbc9487b7, BRF_GRA },
 	{ "61",					0x200000, 0xb813a1b1, BRF_GRA }
 };
 
@@ -2158,8 +2158,8 @@ static struct BurnRomInfo sfiii2bhRomDesc[] = {
 	{ "31",			0x200000, 0x7470a6f2, BRF_GRA },
 	{ "40",			0x200000, 0x01a85ced, BRF_GRA },
 	{ "41",			0x200000, 0xfb346d74, BRF_GRA },
-	{ "50,			0x200000, 0x32f79449, BRF_GRA },
-	{ "51",			0x200000, 0x1102b8eb, BRF_GRA },
+	{ "50",			0x200000, 0x32f79449, BRF_GRA },
+	{ "51",			0x200000, 0x1102b8eb, BRF_GRA }
 };
 
 STD_ROM_PICK(sfiii2bh)
```
below has too many parameters hope this helps always good to see new people helping out.

struct BurnDriver BurnDrvSfiii2bh = {
	"sfiii2", NULL, NULL, NULL, "1997",
	"Street Fighter III 2nd Impact: Giant Attack (Boss Hack)", NULL, "Capcom", "CPS-3",
	NULL, NULL, NULL, NULL,
	BDF_GAME_WORKING | BDF_16BIT_ONLY | BDF_CLONE | BDF_HACK, BDF_HISCORE_SUPPORTED, 2, HARDWARE_CAPCOM_CPS3, GBF_VSFIGHT, FBF_SF,
	NULL, sfiii2bhRomInfo, sfiii2bhRomName, NULL, NULL, NULL, NULL, cps3InputInfo, sfiiiwideusaDIPInfo,
	sfiii2Init, cps3Exit, cps3Frame, DrvCps3Draw, cps3Scan, &cps3_palette_change, 0x40000,
	384, 224, 4, 3
};

**Comment by barbudreadmon** [comment]
Also missing bios, bad name/parent, and the additional roms probably won't be loaded. As i said the best course of action is to build locally and test first...

**Pull request closed without merging**
