### PR TITLE
multiple hiscores added

### PR DESCRIPTION
**Pull request by shaunquick**
naughtyb,naughtyba, naughtybb, naughtybc, popflame, popflamea, popflameb, popflamen, nitedrvr, omegrace, olibochu,
drivfrcp,8bpm, porky, phoenix, phoenix2, phoenixa, phoenixb, phoenixdal, phoenixt, phoenixj, phoenix3, 
phoenixc, phoenixc2, phoenixc3, phoenixc4, phoenixgu, phoenixha, fenixn, condor, condorn, falcon, 
vautour, , falconz, vautourz, avefenix, avefenixrf, , griffon, nextfase, phoenixs, 
phoenixass, pleiads, pleiadsb2, pleiadbl, pleiadce, pleiadsi, pleiadss, 
pitnrun, popper, psychic5, psychic5j, 

should cityatta, capitol, pleiadsn, avefenixl, vautourza, omegrace2 and omegrace3 be in hiscore.dat ? or are hiscores held in nvram (if so how would I tell?).

naughtyb,naughtyba, naughtybb, naughtybc, popflame, popflamea, popflameb, popflamen, nitedrvr, omegrace - although hiscores files are created - the game itself does not transfer the current score to the high score and hence not working as expected.

Query - 8ballact - althuogh in hiscore.dat - there is no BDF_GAME_WORKING flag in the struct BurnDriver - i have not tried to add hiscores as I assume that the flag has to be set before adding hiscores - is that correct ?

### CODE REVIEW

**Comment by shaunquick** [comment]
speedbal is not creating a hiscore file after game exit

**Comment by dinkc64** [comment]
naughtyb and games in it's driver: the game moves the top player's high score to the highscore spot after a new game is started.

**Comment by dinkc64** [comment]
speedbal well, after getting a highscore, it never appears to write the stuff that hiscore.dat is looking for in order to validate the game.  

If a game stores HS in nvram, the HSs will save/load with the fbneo setting "Save High Scores when supported" disabled, for example, early Atari games do this (Centipede, Millipede, Tempest, etc)

I'd suggest using the debug version of fbneo, and putting on the "Misc -> Options -> Show debug console", this will tell you the state of the highscore engine, and what it's up to, why it didn't save the memory and so forth.

best regards,
- dink

**Comment by shaunquick** [comment]
thanks for the reply - i'll look into it (debug) hopefully at some stage, after I have added hiscores to games where it is yet to be done.

On that point - has anyone written a script to identify which games should have Hiscore support add to the .cpp - if not, that will probably be my next task.

Thanks,

ShaunQuick

**Comment by dinkc64** [comment]
you're welcome!

Well, you'd be the first to write such a thing! :)

best regards,
- dink

**Pull request merged**
