### PR TITLE
burn.cpp: fix incomplete string copy

### PR DESCRIPTION
**Pull request by taoenwen**

### CODE REVIEW

**Comment by dinkc64** [comment]
Hi,
can you show me what you're doing to replicate the issue?  I'm asking because wcscpy() does copy the terminating null, but in cases when it doesn't, it might be a far more serious issue (OOB etc)

best regards,
- dink

**Comment by taoenwen** [comment]
image
L"Guardians\0\u96FB\u795E\u9B54\u584A \uFF29\uFF29\0" It will stop after "Guardians".

**Comment by dinkc64** [comment]
oh, I see - nevermind then :)

**Comment by barbudreadmon** [comment]
How come there is a `\0` in the middle of this description ?

I've seen quite a few of them too in the non-unicode descriptions, and replaced them since they simply didn't seem to work in the contexts where `BurnDrvGetTextA(DRV_FULLNAME)` is called.

**Comment by dinkc64** [comment]
barbudreadmon, it puts a little "dot" between the ascii name and non-ascii name, see:
(feature?)

gamelist

**Comment by dinkc64** [comment]
@taoenwen, did you notice all the stray CR (\r or 0x0d) in the code?

stray_cr

**Comment by taoenwen** [comment]
@dinkc64 I can't see the difference between them in the VS editor, so it looks like I should use LF to solve them

**Comment by taoenwen** [comment]
I'll fix them right away.

**Comment by taoenwen** [comment]
https://github.com/finalburnneo/FBNeo/pull/1596

@dinkc64 It's okay.

**Pull request merged**
