### PR TITLE
Street Fighter III HBMame

### PR DESCRIPTION
**Pull request by MavisCelus19201**
sourced from hbmame down to checksum and filenames, looked to try and fix quotes, parenthesis and commas compared to last time, my system isn't strong enough to compile without crashes so it's hard to test. not sure on parameters so i'm looking back and forth for comparison.

### CODE REVIEW

**Comment by barbudreadmon** [comment]
>my system isn't strong enough to compile without crashes so it's hard to test

I can't imagine how it could be possible since even a old raspberry pi model can build this. This PR won't build because part of the issues i mentioned last time are still there.
We won't accept those PRs as long as you don't test it locally and make sure everything works properly (meaning it builds and the hidden characters are actually available).

**Comment by MavisCelus19201** [comment]
> > my system isn't strong enough to compile without crashes so it's hard to test
> 
> I can't imagine how it could be possible since even a old raspberry pi model can build this. This PR won't build because part of the issues i mentioned last time are still there.
> We won't accept those PRs as long as you don't test it locally and make sure everything works properly (meaning it builds and the hidden characters are actually available).

my only system is a weak 32bit windows system and i've had trouble getting githubs tools working with that, not sure if it's too weak or just the 32bit archetecture, though in a few months i'm hoping to upgrade, I'll try getting it working in the meantime though it's been a few years since id messed with this, so apologies if i'm rusty.

**Comment by dinkc64** [comment]
Hi MavisCelus19201,
Thanks for the PR, I found 2 problems that need to be fixed before we can merge it:
1: line 2174, "BDF_HACK, BDF_HISCORE_SUPPORTED", remove the ", BDF_HISCORE_SUPPORTED"
2: line 2171, the first entry in the BurnDriver struct is the romset name, that needs to be changed to "sfiii2bh".  The second entry needs to be "sfiii2", which is the parent romset name (since it is a clone, it needs a parent link)

when you're done, the struct should look like this:
struct BurnDriver BurnDrvSfiii2bh = {
	"sfiii2bh", "sfiii2", NULL, NULL, "1997",
	"Street Fighter III 2nd Impact: Giant Attack | Boss Hack\0", NULL, "hack", "CPS-3",
	NULL, NULL, NULL, NULL,
	BDF_GAME_WORKING | BDF_16BIT_ONLY | BDF_CLONE | BDF_HACK, 2, HARDWARE_CAPCOM_CPS3, GBF_VSFIGHT, FBF_SF,
	NULL, sfiii2bhRomInfo, sfiii2bhRomName, NULL, NULL, NULL, NULL, cps3InputInfo, sfiiiwideusaDIPInfo,
	sfiii2Init, cps3Exit, cps3Frame, DrvCps3Draw, cps3Scan, &cps3_palette_change, 0x40000,
	384, 224, 4, 3
};

best regards,
- dink

**Comment by dinkc64** [comment]
p.s. I have a tiny mingw package that can compile fbneo, it even works on my old p4/winxp machine, if you're interested I can find a link.

**Comment by MavisCelus19201** [comment]
> p.s. I have a tiny mingw package that can compile fbneo, it even works on my old p4/winxp machine, if you're interested I can find a link. All you have to do is unzip it, unzip the latest source and run a batch file.

That'd be nice, testing on a weak 32bit system hasn't been simple, it's been a few years since i've messed with this so i'm a little rusty.

I'll try fixing the structure and see if that works, if not then I can try sending checksums if need be, I can confirm the hacks are working on actual HBMame itself so I'm just having trouble putting them into the right structures.

**Comment by dinkc64** [comment]
[mmingw_2.zip](https://github.com/finalburnneo/FBNeo/files/6789045/mmingw_2.zip)

Unzip it, unpack the rar so it makes c:\mingw
grab the latest fbneo code from the green button on our github page "download zip", unzip it to c:\mingw\fbneo  (or somewhere in there)

now from a cmd window:
run \mingw\bin\mingw_start.bat

in the same cmd window:
go to the fbneo code directory where the makefile resides, and read the message from mingw_start.bat

if you want the compile to go a bit faster, edit makefile.mingw and find the line "DEPEND = 1"
change it to "#DEPEND = 1" & save.  do this before the step above!

best regards,
- dink

**Comment by barbudreadmon** [comment]
>I've also tested the hacks in HBMame itself and they do work, I can send screenshots or video if you want any specific proof but I can confirm on that end they work

As i already said, they need a custom loading mecanism which FBNeo doesn't have, i'll link again that custom loading mecanism from HBMAME : https://github.com/Robbbert/hbmame/blob/master/docs/release/src/hbmame/drivers/cps3.cpp#L35-L192

**Comment by dinkc64** [comment]
barbudreadmon, imo he did the hard part is adding the rom struct, I hate doing that.  so that's positive.
If he can't figure out the unscramble part, i'm sure it can be done easily on my side.

**Comment by JacKc029735** [comment]
ips patches using actual MAME and FB Neo sets already exists for those boss hacks and prefectly works. So it is probably useless to add them.

**Comment by MavisCelus19201** [comment]
> ips patches using actual MAME and FB Neo sets already exists for those boss hacks and perfectly works. So it is probably useless to add them.

you mostly see janky prepatched roms or HBmame more than ips for these, they're also usually strict enough that patching doesn't work without adding support, there's a set of battle garegga patches supported in HBMame that didn't work with FBN when i tried them to name a quick example. some of them offer more to them than MAME cheats offer or just work better, the street fighter 3rd strike one from this set allowing Shin Akuma to name an example

**Comment by MavisCelus19201** [comment]
so I got the file ready and fixed, when I tried compiling it manually it didn't throw any errors when It got to the cps3.cpp, is that a good indicator or should I wait till it finishes so I can try the hack out from within FBN? I'm thinking of doing the latter but It's taken about 3 hours to compile so far so I don't know if looking out for errors on the cps section will be faster.

**Comment by dinkc64** [comment]
Just let it keep going until it finishes :)
After it's done compiling everything, it should only take a minute or so when you make a change to a single file.

**Pull request closed without merging**
