### PR TITLE
Add 12-direction analog support for timesold

### PR DESCRIPTION
**Pull request by pjft**
Adding analog and 12-directions support for timesold.

The previous changes had made it work assuming it had 8-directions only, but [a user pointed out it's supposed to be 12 instead](https://retropie.org.uk/forum/topic/32281/lr-fbneo-new-right-stick-controls-for-several-rotary-games/4?_=1649970605485). 

@barbudreadmon this follows the same naming convention as calibr50 for the right analog stick which might require changes in `retro_input.cpp` when porting it over to the libretro fork for it to be automatically configured.

In my case, I simply added to `GameInpSpecialOne` the following:

```
// Time Soldiers
	if ((parentrom && strcmp(parentrom, "timesold") == 0) ||
		(drvname && strcmp(drvname, "timesold") == 0)
	) {
		if (strcmp("Aim X", description) == 0) {
			GameInpAnalog2RetroInpAnalog(pgi, nPlayer, RETRO_DEVICE_ID_ANALOG_X, RETRO_DEVICE_INDEX_ANALOG_RIGHT, description);
		}
		if (strcmp("Aim Y", description) == 0) {
			GameInpAnalog2RetroInpAnalog(pgi, nPlayer, RETRO_DEVICE_ID_ANALOG_Y, RETRO_DEVICE_INDEX_ANALOG_RIGHT, description);
		}
	}
```

and it works, but perhaps your solution was different than mine at the time.

As always, happy to take any suggestions you might have.

Thanks once again, and I hope you're all doing great.

### CODE REVIEW

**Comment by barbudreadmon** [comment]
tested and approved :)

**Comment by pjft** [comment]
Thank you! Happy Friday :)

**Comment by dinkc64** [comment]
pjft, this is really great - nice work! :)

best regards,
- dink

**Comment by pjft** [comment]
By all means - thank you, and keep up the great work :)

**Pull request merged**
