### PR TITLE
Adding NES Game Request "Super Spike V'Ball" as Europe and USA Version (crc32+burnfile+gameinfo+snaps)

### PR DESCRIPTION
**Pull request by theGabrielWest**
### **Request for adding the following NES Game / Versions:**
- Super Spike V'Ball (USA)
- Super Spike V'Ball (Europe)

**1) Rominfo CRC's are:**
USA Version = C2D3F5B3
EUROPE Version = EAC96B20

**2) NES BurnDriver File as File Attachment:**
[Burnfile NES.zip](https://github.com/finalburnneo/FBNeo/files/9699723/Burnfile.NES.zip)

**3) Game informations in JSON format:**
Super Spike V'Ball **(USA):**
_{ "gameid": "nes_ssvbu", "name": "Super Spike V'Ball (USA)", "year": "1990", "publisher": "Nintendo" , "emulator": "fbneo", "available_for": "all", "system": "NES", "ranked": false, "training": false, "genres": ["Sports"] }_

Super Spike V'Ball **(Europe):**
_{ "gameid": "nes_ssvbe", "name": "Super Spike V'Ball (Europe)", "year": "1992", "publisher": "Nintendo" , "emulator": "fbneo", "available_for": "all", "system": "NES", "ranked": false, "training": false, "genres": ["Sports"] }_

**4) Snapshots as File Attachement: (2 per version)**
[Snapshots ssvb.zip](https://github.com/finalburnneo/FBNeo/files/9699732/Snapshots.ssvb.zip)

_hope I've did anything correctly and that you guys can add these gems soon,
kind regards,
GW alias Gabriel West :-)_

### CODE REVIEW

**Comment by barbudreadmon** [comment]
This is the official FBNeo repository, not the license-breaking outdated fork from FC2

**Comment by theGabrielWest** [comment]
Sry guys, but what is the right repository then? Just were following the link in the instructions -Quote- "If the game is not available in Fightcade's FBNeo, please submit a pull request with the RomInfo CRCs & BurnDriver to Fightcade's repository here: https://github.com/fightcadeorg/fightcade-fbneo -Quote ..and this took me exactly here. Anyone can help? thx

**Comment by theGabrielWest** [comment]
P.S.: Would gratefully appreciate, if someone else with visual basic coding skills can add that for me, since I absolutely know nothing about visual basic (in case if the poste was wrong because of typing in code was required there) kind regards

**Comment by barbudreadmon** [comment]
>https://github.com/fightcadeorg/fightcade-fbneo

Here is https://github.com/finalburnneo/FBNeo as you can see at the top of your browser. This is the official repository for the FinalBurn Neo project.

>if someone else with visual basic coding skills

This project is written in C/C++, not VB.

Apparently you aren't using our project, you are using its fork from FC2, which is not maintained by us and is breaking our license so i can't say we have a very good relation with its maintainers. I'll see if we can add those games, but it won't help you much if you are using a fork instead of the official builds from https://github.com/finalburnneo/FBNeo/releases/tag/latest

**Pull request closed without merging**
