### PR TITLE
d_neogeo: samsho2pe bugfixes

### PR DESCRIPTION
**Pull request by Igor-Arabe**
2023-04-16
- Charlotte state defense
- Kyoshiro state defense

Also, **d_pacman: chuckieegg** - romName should be in lowercase + clone tag.

### CODE REVIEW

**Comment by dinkc64** [comment]
chuckie egg isn't a clone of ponpoko, its a totally new game that runs on ponpoko hw

**Comment by Igor-Arabe** [comment]
@dinkc64 check pr again.

**Comment by Loggan92** [comment]
he means to have it in lowercase to be homogenous.

**Comment by dinkc64** [comment]
@Igor-Arabe thanks :)

**Pull request merged**
