### PR TITLE
PS3 Build

### PR DESCRIPTION
**Pull request by crystalct**
Please add makefile for PS3 build

### CODE REVIEW

**Comment by dinkc64** [comment]
The PS3/libretro version can be found here: https://github.com/libretro/FBNeo
or, did I miss something?

**Comment by barbudreadmon** [comment]
Use the fork

**Comment by crystalct** [comment]
Found it :P

**Comment by crystalct** [comment]
Compiled.. OK
But tiring to link it (renamed in libretro_ps3.a) with an object file using /usr/local/cell/host-win32/sn/bin/ps3ppuld.exe i got many errors like:
Command line : error: L0039: reference to undefined symbol `.rfseek' in file libretro_ps3.a(libretro.o)
Command line : error: L0039: reference to undefined symbol `.rfwrite' in file libretro_ps3.a(libretro.o)
.
.
.
libretro.cpp : error: L0039: reference to undefined symbol `.rfwrite' in file libretro_ps3.a(libretro.o)
libretro.cpp : error: L0039: reference to undefined symbol `.rftell' in file libretro_ps3.a(libretro.o)
libretro.cpp : error: L0039: reference to undefined symbol `.rfwrite' in file libretro_ps3.a(libretro.o)
libretro.cpp : error: L0039: reference to undefined symbol `.rfwrite' in file libretro_ps3.a(libretro.o)

etc etc etc
Any help?

**Comment by barbudreadmon** [comment]
All i can say is that the buildbot at xbins is building the ps3 libretro core successfully (see https://github.com/finalburnneo/FBNeo/issues/191), so that's an issue on your end. Anyway those problems are unrelated to FBNeo, and we know nothing about the ps3 sdk in the first place, you should ask somewhere else, maybe the libretro forums ?

**Comment by dinkc64** [comment]
try to find the lib that has rfseek / rfwrite and link it with that lib?

**Comment by grant2258** [comment]
try updating your libretro common to the newest one online the headers there do all sorts of defines

**Comment by barbudreadmon** [comment]
> the lib that has rfseek / rfwrite

They are built from https://github.com/libretro/FBNeo/blob/573f02385edb8e1b51d9b71bce566ab42b9e4223/src/burner/libretro/Makefile.common#L199-L200
With the xbins guys able to build this from the fork, it's definitely some kind of sdk setup issue, @crystalct should ask help from ps3 libretro experts.

**Comment by dinkc64** [comment]
we can only guess since we don't deal with the ps3 port at all.

**Comment by crystalct** [comment]
There is a variable about static links inside the makefile to compile some common-libs. Setted that no link problems!
Thanks for the help.
@dinkc64: there many people that love to play retro games with PS3.... you make them (and me) happy with your works.

**Pull request closed without merging**
