### PR TITLE
Street Fighter III HBMame

### PR DESCRIPTION
**Pull request by MavisCelus19201**
as per suggestions, i cleaned up the sections, confirmed the hacks work via HBMame and aren't just glitched, fixed some commas and parameters, compiled the program from source and it compiled fully, I also changed it from GRA to ESS to see if that prevents any graphics errors, it seemed overkill to add all the files plus the hack files and looking at other .cpp files that have hacks, it seemed unnecessary though i'm unsure if the CPS3 is different in that regard or if it's mandatory to add the base files alongside the hack files for it.
If needed I can go back and put the files in those sections, looked to make sure spacing wasn't an issue via 3 editors though It's hard to spot.

Had to wipe and try again since it tried merging a bunch of copies of itself into one, not sure why it tried doing that but wiping and trying again should have fixed that.

### CODE REVIEW

**Comment by barbudreadmon** [comment]
Why remove the original simm files ? Are the hack files totally replacing content of original simms ? I can't imagine the second romset to work without the sh2 bios ? Even if that was really the case i wouldl ask that the original files are put in the romsets with the BRF_OPT flag. Did you actually test the program after it compiled fully, as i asked ?
You still didn't address the size issue, neither the missing HARDWARE_CAPCOM_CPS3_NO_CD flag in the second romset.

**Comment by MavisCelus19201** [comment]
> Why remove the original simm files ? Are the hack files totally replacing content of original simms ? I can't imagine the second romset to work without the sh2 bios though. Even if that was really the case (i really doubt it is), by policy we still keep the files present in the original MAME/HBMAME romset that we don't need and add a BRF_OPT flag to them.
> Did you actually test the program after it compiled fully, as i asked ?
> You still didn't address the size issue, neither the missing HARDWARE_CAPCOM_CPS3_NO_CD flag in the second romset.

For SFIII 2 the second one doesn't come with the sh2 bios while 3rd strikes did which is why that doesn't show up in there, I can go back and add the simm/sh2 files if need be if that's policy, i'm a little rusty so i apologize on that one so i forget off hand if you needed all the original parent files when adding in a hack or if you only needed the hack files in that specific set. I recall that being the case with systems like the CPS2 where it's organized with just the hack files though i'm unsure if the CPS3 differs there. 

I did test the program after it compiled fully yes, it gave a size error citing graphics, going back to the .cpp I think i set the flag to the wrong value, BRF_GRA so I did go in and change that so I had to go in and adjust the right flags, it took about 4 hours to compile it altogether since my system isn't very fast so testing it hasn't been efficient. I didn't catch the missing flag though so I can fix that one., I'm gonna try another round of it soon to do more testing though I can't guarantee it'll be quick.

**Comment by barbudreadmon** [comment]
>For SFIII 2 the second one doesn't come with the sh2 bios while 3rd strikes did which is why that doesn't show up in there, I can go back and add the simm/sh2 files if need be if that's policy, i'm a little rusty so i apologize on that one so i forget off hand if you needed all the original parent files when adding in a hack or if you only needed the hack files in that specific set. I recall that being the case with systems like the CPS2 where it's organized with just the hack files though i'm unsure if the CPS3 differs there.

The BurnRomInfo struct must contain the totality of the roms required for the game to boot, what happens in the zip files of a split romset is irrelevant if that's what you were wondering about.

**Comment by JacKc029735** [comment]
As i said those sets are useless to be added. IPS patches already exists for those boss hacks done by Yumeji which enable Hidden characters, 

> sfiii3(__990608)-simm1.0	sfiii3\char-1_0	CRC(11dfd3cd)
> sfiii3(__990608)-simm1.1	sfiii3\char-1_1	CRC(c50585e6)
> sfiii3(__990608)-simm1.2	sfiii3\char-1_2	CRC(8e011d9b)
> sfiii3(__990608)-simm1.3	sfiii3\char-1_3	CRC(dca8d92f)
> 
> [en_US]
> Enable hidden characters
> 
> Hacker: yumeji
> 
> Description: Enabled Akuma & Gill

```
sfiii2-simm1.0	sfiii2\char-1_0	CRC(2d666f0b)
sfiii2-simm1.1	sfiii2\char-1_1	CRC(2a3a8ef6)
sfiii2-simm1.2	sfiii2\char-1_2	CRC(161d2206)
sfiii2-simm1.3	sfiii2\char-1_3	CRC(87ded8a3)

[en_US]
Enable hidden characters v1

Hacker: yumeji

Description:
```

In HBMAME those sets are ;
- Street Fighter III 3rd Strike: Fight for the Future (Enable Hidden Characters) [sfiii3bh] "Yumeji"
- Street Fighter III 2nd Impact: Giant Attack (Enable Hidden Characters V1) [sfiii2bh] "Yumeji"

**Comment by dinkc64** [comment]
JacKc please post the ips file zips here?

**Comment by JacKc029735** [comment]
Here the ips files. Tested and works fine with latest build [see attached file]

[sfiii_ips.zip](https://github.com/finalburnneo/FBNeo/files/6795521/sfiii_ips.zip)

**Comment by MavisCelus19201** [comment]
> Here the ips files. Tested and works fine with latest build [see attached file]
> 
> [sfiii_ips.zip](https://github.com/finalburnneo/FBNeo/files/6795521/sfiii_ips.zip)

I only get errors after patching since it doesn't recognize the checksums, usually it's fairly strict on the crc check, though maybe I'm not patching them right since arcade is usually tricky with this, I recall having similar issues with Battle Gareggas Zack patches a while back.

**Comment by JacKc029735** [comment]
You don't have to patch anything. Just put the ips folders in support folder like this;

image

then when 

image

**Comment by MavisCelus19201** [comment]
> You don't have to patch anything. Just put the ips folders in support/ips folder like this;
> 
> image
> 
> then when you want to load sfiii2 for example, click on **IPS Manager** and don't forget to click on **Apply Patches** like this :
> 
> image
> 
> image
> 
> Click **OK** and lauch the game. The IPS patches will be applied and here the result;
> 
> sfiii2-07-10-195146
> sfiii2-07-10-195221
> 
> That's all :)
> 
> As you can see sometimes it is useless to add some hacks when IPS Patches can do the job.

Ah I see, I've used LunarIPS for console hacks for long enough I'm not used to arcade, so that's good.

How many of those ips patches do you have anyway? I know of only one other pack of those and it didn't have any of the two hacks here, ips is hard to track down for these it seems.

**Comment by JacKc029735** [comment]
Not so many:

image

**Comment by MavisCelus19201** [comment]
> Not so many:
> 
> image

Try sending some of the bosses ips if you can, assuming those are in ips, might try some comparisons.

**Comment by dinkc64** [comment]
@JacKc029735  could you please post a zip of your ips's files? :)

**Comment by MavisCelus19201** [comment]
Screenshot (40)

Don't know if I should send them but I converted a bunch of those hacks into ips format, dat making is a slow process but I can confirm they work with softpatching, so that's good :)

**Comment by dinkc64** [comment]
It takes a lot of work to do great things :)
I recommend posting them on the neosource forum, for a bit of exposure and to let others enjoy your work
https://neo-source.com/

best regards,
- dink

**Comment by MavisCelus19201** [comment]
> It takes a lot of work to do great things :)
> I recommend posting them on the neosource forum, for a bit of exposure and to let others enjoy your work
> https://neo-source.com/
> 
> best regards,
> 
>     * dink

Did it now :)

The ips files are in place, I just need to do the dat files, which I got started on a few so far.

I've also got some Donkey Kong hacks though those are total conversions so I don't know if it's better to send an issue for those.

**Pull request closed without merging**
