### PR TITLE
Update d_spectrum.cpp

### PR DESCRIPTION
**Pull request by mobasweet**
Seraphima new version

---

Use proper version of this game which is current and available on developers website.

### CODE REVIEW

**Comment by dinkc64** [comment]
But, is it better than the enhanced final version?

**Comment by CorpseSlayer** [comment]
I ask in zosya.net if they will add the Seraphima_PT EFE and there answer was;

admin says:
no, as it was the same, but with some bugs. we don’t even have that version left.


So in short to answer your question:
> The version you added to FBNeo was basically remove from existence.
is no longer available, at least this is what i get when they say  "we don’t even have that version left"

So my subjection is to update to the latest final version located on
https://www.zosya.net that include the (RU) (PT) (EN) versions.

**Comment by mobasweet** [comment]
> But, is it better than the enhanced final version?

Apparently the efv is an earlier build

**Comment by mobasweet** [comment]
proper size for the rom added

**Pull request closed without merging**
