### PR TITLE
Update Waldo

### PR DESCRIPTION
**Pull request by mobasuite**
This version was updated, also It comes no longer with a Hard Mode, But I included the ES version.

### CODE REVIEW

**Comment by dinkc64** [comment]
something is wrong with your pr, click on the file and see..

**Comment by mobasuite** [comment]
Here is the replaced code at the bottom of the .cpp file :

```

// Waldo's Life (128K) (HB)

static struct BurnRomInfo SpecWaldolifeRomDesc[] = {
	{ "Waldo's Life 128K EN (2022)(Daniel Isoba).tap", 45080, 0x1d914f86, BRF_ESS | BRF_PRG },
};

STDROMPICKEXT(SpecWaldolife, SpecWaldolife, Spec128)
STD_ROM_FN(SpecWaldolife)

struct BurnDriver BurnSpecWaldolife = {
	"spec_waldolife", NULL, "spec_spec128", NULL, "2022",
	"Waldo's Life (128K) (HB)\0", NULL, "Daniel Isoba", "ZX Spectrum",
	NULL, NULL, NULL, NULL,
	BDF_GAME_WORKING | BDF_HOMEBREW, 1, HARDWARE_SPECTRUM, GBF_PLATFORM, 0,
	SpectrumGetZipName, SpecWaldolifeRomInfo, SpecWaldolifeRomName, NULL, NULL, NULL, NULL, SpecInputInfo, SpecDIPInfo,
	Spec128KInit, SpecExit, SpecFrame, SpecDraw, SpecScan,
	&SpecRecalc, 0x10, 288, 224, 4, 3
};

// Waldo's Life 'hard-mode' (128K) (HB)

static struct BurnRomInfo SpecWaldolifehRomDesc[] = {
	{ "Waldo's Life 128K EN hard-mode (2022)(Daniel Isoba).tap", 45080, 0x8f9d21ca, BRF_ESS | BRF_PRG },
};

STDROMPICKEXT(SpecWaldolifeh, SpecWaldolifeh, Spec128)
STD_ROM_FN(SpecWaldolifeh)

struct BurnDriver BurnSpecWaldolifeh = {
	"spec_waldolifeh", "spec_waldolife", "spec_spec128", NULL, "2022",
	"Waldo's Life 'hard-mode' (128K) (HB)\0", NULL, "Daniel Isoba", "ZX Spectrum",
	NULL, NULL, NULL, NULL,
	BDF_GAME_WORKING | BDF_CLONE | BDF_HOMEBREW, 1, HARDWARE_SPECTRUM, GBF_PLATFORM, 0,
	SpectrumGetZipName, SpecWaldolifehRomInfo, SpecWaldolifehRomName, NULL, NULL, NULL, NULL, SpecInputInfo, SpecDIPInfo,
	Spec128KInit, SpecExit, SpecFrame, SpecDraw, SpecScan,
	&SpecRecalc, 0x10, 288, 224, 4, 3
};
```

**Comment by mobasuite** [comment]
Here is the replaced code :

new

`
// Waldo's Life (128K) (HB)

static struct BurnRomInfo SpecWaldolifeRomDesc[] = {
	{ Waldo's Life 128K EN (2022)(Daniel Isoba).tap, 45060, 0xA18F6513, BRF_ESS  BRF_PRG },
};

STDROMPICKEXT(SpecWaldolife, SpecWaldolife, Spec128)
STD_ROM_FN(SpecWaldolife)

struct BurnDriver BurnSpecWaldolife = {
	spec_waldolife, NULL, spec_spec128, NULL, 2022,
	Waldo's Life (128K) (HB)0, NULL, Daniel Isoba, ZX Spectrum,
	NULL, NULL, NULL, NULL,
	BDF_GAME_WORKING  BDF_HOMEBREW, 1, HARDWARE_SPECTRUM, GBF_PLATFORM, 0,
	SpectrumGetZipName, SpecWaldolifeRomInfo, SpecWaldolifeRomName, NULL, NULL, NULL, NULL, SpecInputInfo, SpecDIPInfo,
	Spec128KInit, SpecExit, SpecFrame, SpecDraw, SpecScan,
	&SpecRecalc, 0x10, 288, 224, 4, 3
};

// Waldo's Life ES (128K) (HB)

static struct BurnRomInfo SpecWaldolifesRomDesc[] = {
	{ Waldo's Life 128K ES (2022)(Daniel Isoba).tap, 45060, 0x62890E34, BRF_ESS  BRF_PRG },
};

STDROMPICKEXT(SpecWaldolifes, SpecWaldolifes, Spec128)
STD_ROM_FN(SpecWaldolifes)

struct BurnDriver BurnSpecWaldolifes = {
	spec_waldolifeh, spec_waldolife, spec_spec128, NULL, 2022,
	Waldo's Life ES (128K) (HB)0, NULL, Daniel Isoba, ZX Spectrum,
	NULL, NULL, NULL, NULL,
	BDF_GAME_WORKING  BDF_CLONE  BDF_HOMEBREW, 1, HARDWARE_SPECTRUM, GBF_PLATFORM, 0,
	SpectrumGetZipName, SpecWaldolifehRomInfo, SpecWaldolifehRomName, NULL, NULL, NULL, NULL, SpecInputInfo, SpecDIPInfo,
	Spec128KInit, SpecExit, SpecFrame, SpecDraw, SpecScan,
	&SpecRecalc, 0x10, 288, 224, 4, 3
};`

old
`
// Waldo's Life (128K) (HB)

static struct BurnRomInfo SpecWaldolifeRomDesc[] = {
	{ "Waldo's Life 128K EN (2022)(Daniel Isoba).tap", 45080, 0x1d914f86, BRF_ESS | BRF_PRG },
};

STDROMPICKEXT(SpecWaldolife, SpecWaldolife, Spec128)
STD_ROM_FN(SpecWaldolife)

struct BurnDriver BurnSpecWaldolife = {
	"spec_waldolife", NULL, "spec_spec128", NULL, "2022",
	"Waldo's Life (128K) (HB)\0", NULL, "Daniel Isoba", "ZX Spectrum",
	NULL, NULL, NULL, NULL,
	BDF_GAME_WORKING | BDF_HOMEBREW, 1, HARDWARE_SPECTRUM, GBF_PLATFORM, 0,
	SpectrumGetZipName, SpecWaldolifeRomInfo, SpecWaldolifeRomName, NULL, NULL, NULL, NULL, SpecInputInfo, SpecDIPInfo,
	Spec128KInit, SpecExit, SpecFrame, SpecDraw, SpecScan,
	&SpecRecalc, 0x10, 288, 224, 4, 3
};

// Waldo's Life 'hard-mode' (128K) (HB)

static struct BurnRomInfo SpecWaldolifehRomDesc[] = {
	{ "Waldo's Life 128K EN hard-mode (2022)(Daniel Isoba).tap", 45080, 0x8f9d21ca, BRF_ESS | BRF_PRG },
};

STDROMPICKEXT(SpecWaldolifeh, SpecWaldolifeh, Spec128)
STD_ROM_FN(SpecWaldolifeh)

struct BurnDriver BurnSpecWaldolifeh = {
	"spec_waldolifeh", "spec_waldolife", "spec_spec128", NULL, "2022",
	"Waldo's Life 'hard-mode' (128K) (HB)\0", NULL, "Daniel Isoba", "ZX Spectrum",
	NULL, NULL, NULL, NULL,
	BDF_GAME_WORKING | BDF_CLONE | BDF_HOMEBREW, 1, HARDWARE_SPECTRUM, GBF_PLATFORM, 0,
	SpectrumGetZipName, SpecWaldolifehRomInfo, SpecWaldolifehRomName, NULL, NULL, NULL, NULL, SpecInputInfo, SpecDIPInfo,
	Spec128KInit, SpecExit, SpecFrame, SpecDraw, SpecScan,
	&SpecRecalc, 0x10, 288, 224, 4, 3
};`

**Comment by mobasuite** [comment]
gimme a minute

**Pull request closed without merging**
