### PR TITLE
d_nes.cpp - Big Endian fix

### PR DESCRIPTION
**Pull request by crystalct**

### CODE REVIEW

**Comment by barbudreadmon** [comment]
how does it perform on ps3 ?

**Comment by crystalct** [comment]
Really unplayable ... 
image

**Comment by crystalct** [comment]
10-20 FPS

**Comment by crystalct** [comment]
An 8 bits so slow? It's so weird....

**Comment by mobasuite** [comment]
Your running NES on a linux computer.

**Pull request merged**
