### PR TITLE
move kaillera chat key

### PR DESCRIPTION
**Pull request by barbudreadmon**
A user with hand disability asked if we could move that key to make things nicer for keyboard users. Is that change fine for everyone ?

### CODE REVIEW

**Comment by tmaul** [comment]
Sounds reasonable to me, although I'm not a netplay user.

**Review by tmaul — APPROVED** [review]

**Comment by dinkc64** [comment]
VK_OEM2 is the / key, right?  I like that idea.  But:
we have to update any references to it.  Is it in the manual, if so, change that also.

**Comment by barbudreadmon** [comment]
Yes, that's the /? key.

fba.chm is totally blank for me ?

**Comment by mobasuite** [comment]
why not update fba.chm to fbn.chm, thx

**Pull request merged**
