### PR TITLE
win32: fix neogeo ghosting in msvc

### PR DESCRIPTION
**Pull request by taoenwen**
image

### CODE REVIEW

**Comment by dinkc64** [comment]
I think the bug is actually earlier in the code, let's not merge this yet :)

**Comment by dinkc64** [comment]
@taoenwen, in VS could you try to put a watch on nShowMVSCartsOnly and see when it returns !0 ?

**Comment by taoenwen** [comment]
nShowMVSCartsOnly is non-zero only when cartridge(s) is selected.
image
image
image

nShowMVSCartsOnly is always 0 when [load game] is done directly.
image

**Comment by dinkc64** [comment]
@taoenwen,
so, It's very curious - why is nShowMVSCartsOnly non-zero in DoExtraFilters():
if (nShowMVSCartsOnly && ((BurnDrvGetHardwareCode() & HARDWARE_PREFIX_CARTRIDGE) != HARDWARE_PREFIX_CARTRIDGE)) return 1;

I will try to install VS 2022 on my win7 pc and try to figure it out, maybe its a memory leak?  (other variable leaking onto nShowMVSCartsOnly)
f.ex something like this:

int abc[2];
static int nShowMVSCartsOnly
...
abc[3] = 1;

best regards,
- dink

**Comment by dinkc64** [comment]
I installed vs 2022,  built x64 Release and Debug version of fbneo and this problem of Igor_Arabe doesn't exist.. hmmm..
When I tried to build x86 (win32) in VS 2022, some strange errors about generated files - Do you have luck to build 32bit exe?

VS2022 warnings+error when attempting to build:
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(247,5): warning MSB8065: Custom build for item "..\..\src\burn\drv\capcom\ctv_make.cpp" succeeded, but specified output "c:\users\fps\desktop\igor\fbneo-master\projectfiles\generated\ctv.h" has not been created. This may cause incremental build to work incorrectly.
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(247,5): warning MSB8065: Custom build for item "..\..\src\burn\drv\pgm\pgm_sprite_create.cpp" succeeded, but specified output "c:\users\fps\desktop\igor\fbneo-master\projectfiles\visualstudio-2022\pgm_sprite.h" has not been created. This may cause incremental build to work incorrectly.
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(247,5): warning MSB8065: Custom build for item "..\..\src\cpu\m68k\m68kmake.c" succeeded, but specified output "c:\users\fps\desktop\igor\fbneo-master\projectfiles\visualstudio-2022\m68kmake.exe" has not been created. This may cause incremental build to work incorrectly.
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(247,5): warning MSB8065: Custom build for item "..\..\src\dep\scripts\build_details.cpp" succeeded, but specified output "c:\users\fps\desktop\igor\fbneo-master\projectfiles\visualstudio-2022\build_details.h" has not been created. This may cause incremental build to work incorrectly.
1>..\..\src\burn\burn_sound_a.asm
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\BuildCustomizations\nasm.targets(68,5): error MSB3721: The command ""C:\Program Files\Microsoft Visual Studio\2022\Community\VC\"nasm.exe -Xvc -f win32 -o "Win32\Release\burn_sound_a.obj"  "C:\Users\FPS\Desktop\igor\FBNeo-master\src\burn\burn_sound_a.asm"" exited with code 1.
1>Done building project "fbneo_vs2022.vcxproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped =======

**Comment by taoenwen** [comment]
Is nasm not configured for msvc? 
https://github.com/ShiftMediaProject/VSNASM. (Simple configuration of NASM compilation environment.)

This is the x86 binary of this PR, compiled yesterday
[fbneod_vs.zip](https://github.com/finalburnneo/FBNeo/files/10471658/fbneod_vs.zip)

This is the x86 binary that was just compiled with this PR removed, and apparently the problem exists
[today_fbneod_vs.zip](https://github.com/finalburnneo/FBNeo/files/10471663/today_fbneod_vs.zip)

**Comment by taoenwen** [comment]
@dinkc64 I found that this problem only occurs with x86 binary files

**Comment by dinkc64** [comment]
taoenwen. thanks, it works now :)

.. later ..
I ran out of ram while debugging, and vs 2022 completely corrupted itself, well, I won't waste any more time with this sh*t (garbage) compiler system, because installing it took most of yesterday.

findings:
heap (or stack) is getting corrupted, leading to variable being set wrongly. 
this happens because:
a. vs2022 making bad code
b. or a bug in our code
(a||b) || (a&&b) ?  don't know.  Does it work in VS 17 ?  (I mean: real vs 17, not vs22 simulating vs 17)

taoenwen, you're pr might be the only option here for vs 2022, but, what happens when corruption moves to a different variable?

best regards,
- dink

**Comment by dinkc64** [comment]
sorry, i had bad mood earlier, my apologies.

**Comment by taoenwen** [comment]
@dinkc64 I think I found the problem, forced type conversion

**Comment by taoenwen** [comment]
https://github.com/finalburnneo/FBNeo/pull/1313

**Comment by dinkc64** [comment]
very nice, taoenwen!! :)

**Pull request closed without merging**
