### PR TITLE
nes add some t-chi games

### PR DESCRIPTION
**Pull request by taoenwen**
Thanks！ barbudreadmon

### CODE REVIEW

**Comment by barbudreadmon** [comment]
i'm kinda confused here, that zelda is not a hack of the original zelda ?

**Comment by taoenwen** [comment]
https://www.ppxclub.com/forum.php?mod=viewthread&tid=711227&extra=&page=1
From the perspective of file size, it should be converted from FDS, and the actual test is mapper 01.
image
Normal operation
image
image
image
image

**Comment by barbudreadmon** [comment]
I believe you are supposed to use "fds_zeldanoden" as parent in that situation, even if they run on different systems, iirc we got a similar situation for some romset on sms/gg. Let's wait for @dinkc64's feedback about this.

**Comment by dinkc64** [comment]
just make it a clone of nes_legenzel

**Comment by taoenwen** [comment]
nes_zeldanodenc clone to nes_legenzel

**Comment by dinkc64** [comment]
:)

**Pull request merged**
