### PR TITLE
NEO GEO Secret Character Additions

### PR DESCRIPTION
**Pull request by WandeingLagomorph793**
Sourced from AdmiralMcFish: https://www.youtube.com/user/AdmiralMcFish

### CODE REVIEW

**Comment by dinkc64** [comment]
Hi,
There's a couple issues in your pr that won't compile, but they shouldn't be too hard to fix.
first, the romset structure name you've used is conflicting with the original in some games, for example:
"static struct BurnRomInfo sdodgebRomDesc[] = {" needs to be "static struct BurnRomInfo sdodgebhRomDesc[] = {"

a comment line always needs to have // in-front of it :)

 can you tell where to get these new rom or patches so we can try them before merging?

did you try compiling this on your computer?  Compiler will sometimes give good hints as to where the problems are :)

best regards,
- dink

**Comment by WandeingLagomorph793** [comment]
> 
> 
> Hi,
> There's a couple issues in your pr that won't compile, but they shouldn't be too hard to fix.
> first, the romset structure name you've used is conflicting with the original in some games, for example:
> "static struct BurnRomInfo sdodgebRomDesc[] = {" needs to be "static struct BurnRomInfo sdodgebhRomDesc[] = {"
> 
> a comment line always needs to have // in-front of it :)
> 
> can you tell where to get these new rom or patches so we can try them before merging?
> 
> did you try compiling this on your computer? Compiler will sometimes give good hints as to where the problems are :)
> 
> best regards,
> 
>     * dink

Ah gotcha. I did try compiling on my end and looking through commits to make sure things were good, I must have gotten something mixed up in there.

Don't know if I can link them but most of the ones on there are from the user listed above, he does alot of hidden character showcases. he has a link containing a ton of these, I don't know if i can send a direct link but I'll see if he has it in one of the videos.

**Comment by WandeingLagomorph793** [comment]
https://mega.nz/#!oYAXRJaS!crCp9AlUr4U19DoidUkt6L5lJtt6E19mJmpX-gHMcfo

Found the link here, he covers a ton of these secret character and boss hacks, Super Dodge Ball isn't in that list so I'll see if I can find that one separately

**Comment by dinkc64** [comment]
Thanks :)

**Comment by WandeingLagomorph793** [comment]
> 
> 
> Thanks :)

No problem :), Magical Drop III and Super Dodge Ball are from separate sources, i'll see if I can refind the links, if I can't I'll try and figure something out, I might have them locally.

**Comment by WandeingLagomorph793** [comment]
> 
> 
> Thanks :)

https://mega.nz/#F!NgYWAQJA!uHxD3JARZkWcfD4np_hWKg

Got some files compiled here, I've been trying to set these up in a PR for a while, I keep running into conflicts when I try it, I look around to follow the right format but I think I'm missing something and I don't know what, even looking at commits to compare.

**Comment by dinkc64** [comment]
Here's what I found in your PR, replace "old:" line with "new:" :)  (only in your code, not anywhere else in the source file)

old: static struct BurnRomInfo sdodgebRomDesc[] = {
new: static struct BurnRomInfo sdodgebhRomDesc[] = {

old: static struct BurnRomInfo magdrop3RomDesc[] = {
new: static struct BurnRomInfo magdrop3bhRomDesc[] = {

old: struct BurnDriver BurnDrvmagdrop3 = {
new: struct BurnDriver BurnDrvmagdrop3bh = {

old: struct BurnDriver BurnDrvwakuwak7 = {
new: struct BurnDriver BurnDrvwakuwak7bh = {

old: Real Bout Fatal Fury 2 - The Newcomers / Real Bout Garou Densetsu 2 - the newcomers (Secret Character Hack) (NGM-2400)
new: // Real Bout Fatal Fury 2 - The Newcomers / Real Bout Garou Densetsu 2 - the newcomers (Secret Character Hack) (NGM-2400)

old: struct BurnDriver BurnDrvrbff2 = {
new: struct BurnDriver BurnDrvrbff2bh = {

old: NULL, rbff2bhRomInfo, rbff2RomName, NULL, NULL, NULL, NULL, neogeoInputInfo, neogeoDIPInfo,
new: NULL, rbff2bhRomInfo, rbff2bhRomName, NULL, NULL, NULL, NULL, neogeoInputInfo, neogeoDIPInfo,

old: struct BurnDriver BurnDrvrbffspec = {
new: struct BurnDriver BurnDrvrbffspbh = {

best regards,
- dink

**Comment by WandeingLagomorph793** [comment]
> 
> 
> Here's what I found in your PR, replace "old:" line with "new:" :) (only in your code, not anywhere else in the source file)
> 
> old: static struct BurnRomInfo sdodgebRomDesc[] = {
> new: static struct BurnRomInfo sdodgebhRomDesc[] = {
> 
> old: static struct BurnRomInfo magdrop3RomDesc[] = {
> new: static struct BurnRomInfo magdrop3bhRomDesc[] = {
> 
> old: struct BurnDriver BurnDrvmagdrop3 = {
> new: struct BurnDriver BurnDrvmagdrop3bh = {
> 
> old: struct BurnDriver BurnDrvwakuwak7 = {
> new: struct BurnDriver BurnDrvwakuwak7bh = {
> 
> old: Real Bout Fatal Fury 2 - The Newcomers / Real Bout Garou Densetsu 2 - the newcomers (Secret Character Hack) (NGM-2400)
> new: // Real Bout Fatal Fury 2 - The Newcomers / Real Bout Garou Densetsu 2 - the newcomers (Secret Character Hack) (NGM-2400)
> 
> old: struct BurnDriver BurnDrvrbff2 = {
> new: struct BurnDriver BurnDrvrbff2bh = {
> 
> old: NULL, rbff2bhRomInfo, rbff2RomName, NULL, NULL, NULL, NULL, neogeoInputInfo, neogeoDIPInfo,
> new: NULL, rbff2bhRomInfo, rbff2bhRomName, NULL, NULL, NULL, NULL, neogeoInputInfo, neogeoDIPInfo,
> 
> old: struct BurnDriver BurnDrvrbffspec = {
> new: struct BurnDriver BurnDrvrbffspbh = {
> 
> best regards,
> 
>     * dink

Thanks :)

Do I just submit it as another PR or do I merge it in with this one?
Also I'll try and add in the other hacks as well, what's the format? I want to make sure so I don't miss something somehow.

**Comment by dinkc64** [comment]
Just put it here, that's fine.
Compilation is still failing, try to move your code to the bottom of the source file :)

**Comment by WandeingLagomorph793** [comment]
> 
> 
> Just put it here, that's fine.
> Compilation is still failing, try to move your code to the bottom of the source file :)

Bottom of the source file, I'm guessing that's with the *original* d_neogeo.cpp with all the code? Does the specific order matter? Trying to make sure I do it right so I apologize for all the questions.

**Comment by dinkc64** [comment]
Yes, just take everything you've added and move it to the bottom of d_neogeo.cpp.  If you'd like to you can do it a bit more organized and put each entry under the parent game.  The order doesn't really matter unless you want to make it look nice, but that's up to you.

**Comment by WandeingLagomorph793** [comment]
> 
> 
> Yes, just take everything you've added and move it to the bottom of d_neogeo.cpp. If you'd like to you can do it a bit more organized and put each entry under the parent game. The order doesn't really matter unless you want to make it look nice, but that's up to you.

Hey it worked! Had to edit something closer to the bottom due to a paste error (accidentally left a "new"), looks like all the checks passed for this one, thanks :)

I'll try and organize another one later on with the rest of these hacks, There's some Capcom hacks as well, I'm looking at that cpp file now but I'm guessing it's pretty similar there?

**Comment by dinkc64** [comment]
Hi, sorry for taking so long, but I had to fix a few things.  :)  I'll have a final version for you in an hour or 2.

**Comment by dinkc64** [comment]
I can only seem to find magdrop3bh and spdodgebh, I need wakuwak7bh, rbff2bh and rbffspbh romsets so I can test out the code.

best regards,
- dink

**Comment by WandeingLagomorph793** [comment]
> 
> 
> I found all the romsets.. finally :)
> 
> best regards,
> 
>     * dink

Hey thanks :).

I'll try and arrange a file to snag some remaining hacks for the Neo Geo, alongside Capcom and a couple smaller ones (One's Asura Buster), bit on the busy side in a week so it might take some time, not to mention comparing data, but then I'll have something set up there, thanks for the help too :)

**Comment by dinkc64** [comment]
You're welcome :)

I got everything working properly and set up the parent/clone relationships.  I just need you to do one last thing, grab the file attachment below - the zipped d_neogeo.cpp, unzip it and close this PR.  Now create another PR with the new d_neogeo.cpp file.  For some reason this PR things you re-wrote every single line in d_neogeo.cpp, and I'd like to avoid that :)
[d_neogeo.zip](https://github.com/finalburnneo/FBNeo/files/4176492/d_neogeo.zip)

best regards,
- dink

**Comment by WandeingLagomorph793** [comment]
> 
> 
> You're welcome :)
> 
> I got everything working properly and set up the parent/clone relationships. I just need you to do one last thing, grab the file attachment below - the zipped d_neogeo.cpp, unzip it and close this PR. Now create another PR with the new d_neogeo.cpp file. For some reason this PR thinks you re-wrote every single line in d_neogeo.cpp, and I'd like to avoid that :)
> [d_neogeo.zip](https://github.com/finalburnneo/FBNeo/files/4176492/d_neogeo.zip)
> 
> best regards,
> 
>     * dink

Got it :)
Is it just uploading with a new PR or do I also copy paste into another d_neogeo.cpp to prevent any errors?

**Comment by dinkc64** [comment]
Just copy the file over your old d_neogeo.cpp or upload it to the PR,  Don't copy and paste the data from inside the file please :)

**Pull request closed without merging**
