### PR TITLE
update cps1

### PR DESCRIPTION
**Pull request by taoenwen**
pang3b2 fixes the graphics and is now working
gulunpa patch first byte of ROM 4 pending redump
sfach & sfzbch emove unavailable driver tags
add Hello Kitty Magical Pumpkin (Japan 960712), not working (needs 'wheel' emulation)

### CODE REVIEW

**Comment by taoenwen** [comment]
> very nice! I'll try to add wheel for hkittymp soon!

@dinkc64 Thank you very much！

**Comment by 7zxkv** [comment]
hi,

 just little fix: good name of sfbch23 (crc:53699f68) is sfz**b**ch23 (conform to mame). Thanks.

**Comment by 7zxkv** [comment]
hi,

 just little fix: good name of sfbch23 (crc:53699f68) is sf**z**bch23 (conform to mame). If anyone can edit this thanks ;)

**Comment by dinkc64** [comment]
Sure 7zxkv :)

**Comment by taoenwen** [comment]
> hi,
> 
> just little fix: good name of sfbch23 (crc:53699f68) is sf**z**bch23 (conform to mame). If anyone can edit this thanks ;)
> 
> @dinkc64 @taoenwen

@7zxkv thanks

**Comment by dinkc64** [comment]
I figured out the encoding for hello kitty's wheel, it's a simple quadrature encoder

**Comment by taoenwen** [comment]
> I figured out the encoding for hello kitty's wheel, it's a simple quadrature encoder

I have another opportunity to learn from you!

**Comment by dinkc64** [comment]
First part: find out which bits are used.
I went into service mode, first option to see the inputs - pressing left / right will light up the Handle-L and Handle-R.  This means encoder is on first 2 bits (f.ex:)
 	{"P1 Left"          , BIT_DIGITAL  , CpsInp001+1, "p1 left"   },
 	{"P1 Right"         , BIT_DIGITAL  , CpsInp001+0, "p1 right"  },

Before I knew it was an encoder, I tried setting up a simple analog counter/input on those 2 bits (counter&3), but this didn't work.  Then I thought: if it only uses 2 bits, it must be quadrature encoded.  Here, you can find a picture to show how it works:

quadrature

for CW: we'll try A = bit 0 and B = bit 1, so if we decode the first segment, it'll be:
0, 1, 3, 2 (repeat)
CCW:
0, 2, 3, 1 (repeat)
you'll notice, CCW is just the reverse-indexing of CW :)

This picture will show how I got the bits:
quadrature_bits

**Comment by taoenwen** [comment]
> 

Judgment by Hall AC signal, it's amazing

**Pull request merged**
