### PR TITLE
win32: add cmdline for romdata

### PR DESCRIPTION
**Pull request by taoenwen**

### CODE REVIEW

**Comment by dinkc64** [comment]
Just a note:
memset() only sets 1 byte, _T("\0") is 2 bytes
if you have something like
TCHAR szBuf[100];
use this:
memset(szBuf, '\0', sizeof(szBuf));

using sizeof() is a good line of protection in-case the structure size changes

best regards,
- dink

**Comment by taoenwen** [comment]
Thank you for your guidance.
I'll fix it.

**Comment by dinkc64** [comment]
Hi taoenwen,
memset() and malloc() operate @ byte-size, so it is still necessary to specify the size * sizeof(wchar_t) for, example:
pszFullName[i] = (wchar_t*)malloc(MAX_PATH * sizeof(wchar_t));
..
memset(pszFullName[i], '\0', MAX_PATH * sizeof(wchar_t));

best regards,
- dink

**Comment by taoenwen** [comment]
I see. Thank you for taking the time to explain it to me.

**Comment by taoenwen** [comment]
The use of memset() has been fully adjusted
[1] String arrays using sizeof()
[2] malloc the actual length of the requested string.

**Comment by taoenwen** [comment]
yes，sir

**Pull request merged**
