### PR TITLE
d_neogeo.cpp : Add mslug series of hack games

### PR DESCRIPTION
**Pull request by taoenwen**
[RomName.txt](https://github.com/finalburnneo/FBNeo/files/8872480/RomName.txt)

@dinkc64 Hi, dink
The document has been updated with details

### CODE REVIEW

**Comment by dinkc64** [comment]
taoenwen, thank you :)

**Comment by alicemsu** [comment]
@dinkc64 @taoenwen 

Thank you very much for adding these roms hacks to your emulator, now I want to ask you a small favor. I reiterate again to respect the titles of the works. in this case, I am the author of the modifications of the works you see below. it was a dedication from me to my friends of Fightcade 2. So please, add correctly to your emulator and do not suppress the names as they did with the ramake mslug5 version. Sorry for the inconvenience.

RomName: mslug2fm
Friendly Fire (Fightcade 2 Ver.2 Hack)

RomName: mslugxsrf
Metal Slug X AzStar Soda Remix (Fightcade 2 Ver. Hack)

RomName: mslug5sgf 
Metal Slug 5 Remake Final (Fightcade 2 Ver.2021 Hack)

image
image
image

**Comment by dinkc64** [comment]
alicemsu, it's no problem, except in respect to FBNeo developers we must use "FC2" instead of "Fightcade 2" in our game-list

**Comment by alicemsu** [comment]
Thanks @dinkc64, I'll settle

**Comment by taoenwen** [comment]
[1] I noticed the association between mslug5sgf and mslug5sg when I added it yesterday
[2] Here's what I added 2 weeks ago, there's an ips with mslug5sg named [石龟]，Author [小掌饼]
https://github.com/taoenwen/FBNeo_IPS/tree/master/%5B1%5D%20NeoGeo/mslug5
image
[3] This is noted in the attached document
image
image
[4] So, for the unknown, I am cautious
[5] And I remember this version, it existed in the ipses that I cleaned up earlier, if you are interested, you can check the history, and this cleaned up version was still named [石龟]
[6] In summary, the process of adding drivers does not hide anything, some are just unknown

**Comment by barbudreadmon** [comment]
i talked with @alicemsu on discord and made the requested changes in https://github.com/finalburnneo/FBNeo/commit/70aaf0ff348459374c4759cce5587b9dbdbbe00e

**Comment by alicemsu** [comment]
The GOTVG version is very different from the version I have released for FC2. You can try it if you wish. I have also worked with Wan hua and I am in the same hacking group as this one. I have renamed mslug5sgf so my friends can recognize it.
FC2 as version. It will also be released in GOTVG since the Wang version has abandoned it.

**Comment by alicemsu** [comment]
@taoenwen The GOTVG version is very different from the version I have released for FC2. You can try it if you wish. I have also worked with Wan hua and I am in the same hacking group as this one. I have renamed mslug5sgf so my friends can recognize it.
FC2 as version. It will also be released in GOTVG since the Wang version has abandoned it.

**Comment by taoenwen** [comment]
@dinkc64 @alicemsu @barbudreadmon
Now that the misunderstanding is cleared up, that's great

**Comment by alicemsu** [comment]
@taoenwen I have sent you the rom changes via your discord chat.
and what is planned to be added. Wang is very busy. so it's my task. it will take quite a while. Thanks, hope I didn't cause any inconvenience. taoenwen, barbudreadmon, dinkc64

**Pull request merged**
