### PR TITLE
Mapping

### PR DESCRIPTION
**Pull request by grant2258**
@tmaul can you test this out your end. Ill test this properly tomorrow when i get more time dont pull it yet still need to add sf2 mapping should get that done tomorrow you should be able to use your controller to coin up now.

### CODE REVIEW

**Comment by tmaul** [comment]
Cool, I will check it out. My linux PC has developed a bit of problem so just reinstalling that before I can test.

**Comment by grant2258** [comment]
Tested fine with me here as long as sdl2 has the right mapping for your controller you should be good to go.

**Comment by tmaul** [comment]
@grant2258 This seems to work pretty well here, but only tested with a couple of joypads. Shall I merge it in now or are you still adding to it?

**Comment by grant2258** [comment]
passed with the pads i have as well we can fix anything if any issues pop up

**Pull request merged**
