### PR TITLE
Add Cyberbots Access Mod

### PR DESCRIPTION
**Pull request by wrennnnnn**
https://pastebin.com/VbCDxfw0

### CODE REVIEW

**Comment by barbudreadmon** [comment]
This is incomplete, you need a BurnDriver struct, see https://github.com/finalburnneo/FBNeo/commit/12beebd766766ca31bf8685cae405beca745e4b9 for a full example

**Comment by dinkc64** [comment]
Hi, if you don't know how to finish it, please attach the mod here and let us know the name it should be, etc, and we'll take care of it :)

best regards,
- dink

**Comment by arcadez2003** [comment]
He was so close :)

**Comment by wrennnnnn** [comment]
Should be fixed now.

**Comment by dinkc64** [comment]
Almost there: just move the hack tag to "BurnDrvCpsCybotsam" instead of "BurnDrvCpsCybotsu"
and remove the duplicate "struct BurnDriver BurnDrvCpsCybotsjd = { ... }", see:
https://github.com/finalburnneo/FBNeo/pull/921/commits/5a532db36890df8e67699a46987571d3dd201dd9

best regards,
- dink

**Pull request closed without merging**
