### PR TITLE
Precompile instructions to dipswitch

### PR DESCRIPTION
**Pull request by taoenwen**
image

### CODE REVIEW

**Comment by barbudreadmon** [comment]
Why does it require addendum to our dipswitch parsing logic in `gami.cpp` and `inpdipsw.cpp` ? It can't be handled the standard way ? Like i did in https://github.com/finalburnneo/FBNeo/commit/51aab5f05d343d85c63852e8b2f8091fd562ffce, you create a new dip and simply check its value from within the driver ?

**Comment by taoenwen** [comment]
Yes, check the value of dip and change the driver.
The lightest change is equivalent to adding several sets of drivers to the game.

**Comment by barbudreadmon** [comment]
I still don't understand why you can't handle this dip without changing the logic in `gami.cpp`+`inpdipsw.cpp`.
Well, i can't test this since it'll only work in standalone, let's wait for someone else to review your code.

**Comment by taoenwen** [comment]
That's because I didn't find the case you submitted before, I have to study hard.

**Pull request closed without merging**
