### PR TITLE
Rev B of the ROM

### PR DESCRIPTION
**Pull request by mobasuite**
Thanks for reading this, unsure which rev was the OG included in this, but this is the REV B either way.

With Header : 4E 45 53 1A 20 00 E3 10 00 00 00 00 00 00 00 00

### CODE REVIEW

**Comment by dinkc64** [comment]
is that the original header that came with the rom?  if not, can you share the original unmodified header?

**Comment by mobasuite** [comment]
That's what I got from my forum which was dated by the no intro group.

**Comment by mobasuite** [comment]
Here's the file CRC anyway : 

CRC32: | 17812952
MD5: | ffa1023dfa8f887a98d7debb5eab8d09
SHA-1: | 671d0ec8ae8e73a1eaa465687a2c38e0e0747ed4

**Comment by mobasuite** [comment]
NES ROMs don't have watermarks

**Comment by dinkc64** [comment]
thanks
thanks for the extra info Igor-Arabe, one can only wonder what those 4 bytes are for :)

**Pull request merged**
