### PR TITLE
d_wrally.cpp - Big Endian fix

### PR DESCRIPTION
**Pull request by crystalct**

### CODE REVIEW

**Comment by crystalct** [comment]
Despite the eradication of everything that concerns CELLOS_LV2 from Retroarch and cores.... I'll try to keep a my fork working manually, maybe in future a version for PSL1GHT will be usable.
Today was a very sad day.

**Comment by dinkc64** [comment]
It seems like lately nobody has anything good to say about that project.  

Please create a thread on the forum for your project if you'd like, with links to the latest binaries etc.

best regards,
- dink

**Comment by dinkc64** [comment]
Please create a thread on the fbn forum for your project if you'd like, with links to the latest binaries etc.
Hang in there :) 

best regards,
- dink

**Comment by crystalct** [comment]
I will.... meanwile i created a diff file from 55a78db commit to c6c522d commit so i should be able to compile FBNeoCore for PS3 after patching any libretro/FBNeo update (i hope).

**Comment by dinkc64** [comment]
crystalct, it makes me mad

@barbudreadmon - re: the commit crystalct listed above: please don't let that idiot sabotage our source.   I mean, he can on your side if you want him to, but not on this (upstream) side. :)

**Comment by barbudreadmon** [comment]
@crystalct @dinkc64 it turns out there was a very good reason to remove that support : some people are shitstirring about that support in libretro... things will have to stay like this until a better solution is found.

**Pull request merged**
