### PR TITLE
d_neogeo: samsho2pe up to v1.8

### PR DESCRIPTION
**Pull request by taoenwen**
New Update Version 1.8:
-----------------------------
Hurtbox all chars rebalanced in the air for so that when they collide someone gets hit Jumps with punch weak attacks from Sieger, Nicotine, Cham Cham are now blocked by jubei in special move "Shingatou blocked counter",buff! Medium punch attack short now blocked by jubei in special move "Shingatou blocked counter", buff! Hanzo infinite combo removed, jump right + CD attack cancels on ovehead, AB front cancel in mozuto, restarts the same loop, it worked in Earthquake, Sieger, Wanfu, Nerf! Special move Tsubame Rokuren consumes damage on defense in new version, buff! All chars execute command basic Race(Run), in original to cancel and attack in average of 12 or 7 frames, now cancel in 3 frames, buff! Hit counter now predicts the char in a "Aerial Stun" and clear "hit counter" on the screen! Genjuro Remove Combo Jump Attack, Down+AB, Ouzakan, 3 rekka, big damage now the combo no longer exists, nerf! Genjuro Remove Combo Jump Attack, Down+AB, Ouzakan, "Five Flash Rip" in corner, big damage 80%, nerf! Wanfu readjusted damage project special move "Thunder Bomb", Explosion Steam Smoke in counter big damage 70% in original samsho2, rebalanced for 30% damage, nerf! Ukyo Tachibana modified special move "Tsubame Rokuren" to FHCF+AB Genjuro cancel AB stand or down with special moves in stun or block, first frames, buff!   Fixed a bug where Nakoruru had problems to hang on her "Eagle" if it was too far away allowing her to do empty cancels, This bug already exists in the original Samsho2, it made it possible to execute infinite combos, now the eagle runs at high speed along with Nakoruru so it can be used, if it retreats on the backdash the eagle also goes at high speed, only when nakoruru 2x Forward, or 2x Backward

### CODE REVIEW

**Comment by taoenwen** [comment]
Test: https://drive.google.com/drive/folders/1qqk2cNlE5ecb6wMGjJmAqTef2xVgshyJ?usp=sharing

**Comment by dezraj** [comment]
Hello @taoenwen ! Thank you so much for your work in this improved Samurai Shodown 2 version.

Where can we get updated romsets for this game? Is it here in "FBNeo sooner" threads?
https://www.retroroms.info/forum/
Is there another "official" forum for the changes made to this game?

Also, do you keep the archive.org samsho2pe romset updated here?
https://archive.org/details/fbnarcade-fullnonmerged

Thank you so much in advance for any help with these questions. 👍

**Comment by taoenwen** [comment]
@dezraj Google 👆，test …

**Comment by dezraj** [comment]
> @dezraj Google 👆，test …

Yes, I have already downloaded the updated roms. But I want to know if you have a website or forum with updated changes for samsho2pe. For example, here: https://www.retroroms.info/forum/ ?

Do you keep samsho2pe.zip updated here with latest CRC changes: https://archive.org/details/fbnarcade-fullnonmerged ?

Maybe @Igor-Arabe could help me with these questions.

Thank you so much again for your time and help! 👍

**Comment by taoenwen** [comment]
Yes，@Igor-Arabe

**Pull request merged**
