### PR TITLE
Native macOS build

### PR DESCRIPTION
**Pull request by 0xe1f**
Window

Here's some changes to allow building a native macOS version under Xcode. Sound is still SDL-based, but that's OK - most importantly the message loop isn't tied to SDL.

A lot of the video stuff is cannibalized from my other emulator, [FinalBurn X](https://github.com/0xe1f/FinalBurn-X). The icon is also based on the FBX icon, but is blue instead of red:

Icon 

There are several known issues, and I've outlined them all in [README-macOS](https://github.com/0xe1f/FBNeo/blob/macos/README-macOS.md); I'll do my best to resolve most of them in the next few days - as well as provide a `dmg` archive.

Thanks.

### CODE REVIEW

**Comment by pakoito** [comment]
Rejoice!

**Comment by barbudreadmon** [comment]
> There are several known issues, and I've outlined them all in README-macOS;

CPS3 not working might be related to color depth ? Iirc they only work with 16-bits. It might be worth taking a look at my `SetColorDepth` call in https://github.com/libretro/FBNeo/blob/master/src/burner/libretro/libretro.cpp

**Comment by tmaul** [comment]
@0xe1f 
Nice! I'm currently migrating from appveyor to github actions. Any idea what the commandline for compliling this might be? Just asking as there is an OSX host with xcode, so can add this to the automatic builds, and I don't know the password to my macbook.

**Comment by 0xe1f** [comment]
@tmaul from `projectfiles/xcode`, run `xcodebuild -target Emulator -configuration Debug`.
@barbudreadmon it is certainly related to that, thanks. I'll take another look at `SetColorDepth`.

**Comment by 0xe1f** [comment]
Feel free to merge the changes once the build is verified. I'll work on providing a `dmg` archive for download.
@pakoito I'd rather that get fixed properly, with an actual Preferences panel. Joystick/gamepad support is more pressing for me at the moment.

**Comment by tmaul** [comment]
> Feel free to merge the changes once the build is verified. I'll work on providing a `dmg` archive for download.

It's the current build queue item, I deleted all the backlog

**Comment by 0xe1f** [comment]
[Link to the dmg](https://github.com/0xe1f/FBNeo/releases/tag/macos-v1.0)

**Comment by tmaul** [comment]
@0xe1f Any ideas what I am doing wrong with the macos build that would generate this error:

    /bin/sh -c /Users/runner/runners/2.159.2/work/FBNeo/FBNeo/projectfiles/xcode/build/Emulator.build/Debug/Emulator.build/Script-FEA5E7B023564BD600DA2D9D.sh

Error: Couldn't open OUTPUT file /Users/runner/runners/2_table.159.2/work/FBNeo/FBNeo/src/dep/generated/cave_tile_func.h: No such file or directory at /Users/runner/runners/2.159.2/work/FBNeo/FBNeo/projectfiles/xcode/../../src/dep/scripts/cave_tile_func.pl line 26.

Error: Couldn't open OUTPUT file /Users/runner/runners/2_table.159.2/work/FBNeo/FBNeo/src/dep/generated/cave_sprite_func.h: No such file or directory at /Users/runner/runners/2.159.2/work/FBNeo/FBNeo/projectfiles/xcode/../../src/dep/scripts/cave_sprite_func.pl line 26.

**Comment by 0xe1f** [comment]
Sounds like one of the `dep/generated` scripts is failing.

**Comment by 0xe1f** [comment]
@tmaul FWIW, here's what I tried:
1. check out a new copy from FBNeo/master: `git clone git@github.com:finalburnneo/FBNeo`
2. `cd` to the directory: `cd FBNeo/projectfiles/xcode`
3. run build: `xcodebuild -target Emulator -configuration Debug`

It generated `FinalBurn Neo.app` under './build/Debug/`. I did this on my local system, using Xcode 11.

**Comment by tmaul** [comment]
Do you happen to know which version of xcode you are using? And have you
ever set a target beyond emulator?

For some reason it looks like the perl scripts are failing but I am pretty
sure the perl interpreter is installed and running

**Comment by 0xe1f** [comment]
I'm using Xcode 11. There's no other target other than Emulator, it wouldn't work (I tried it just now and got `The project 'Emulator.xcodeproj' does not contain a target named 'foo'.`)

**Comment by tmaul** [comment]
It must be something to do with the set up of xcode in the GitHub action.
The documentation is a bit lacking as to how they have things set up :)

**Comment by 0xe1f** [comment]
The error suggests something with the path; my best guess is that it may be something related to the sandboxed environment.
At some point I plan to update the Xcode build settings to compile the generated headers/code into the derived file directory. When done, I'll let you know so you can try again - maybe that'll fix it.

**Pull request merged**
