### PR TITLE
hiscore support added for alinvade, sstingry, kyros, kyrosj, battlane, battlane2, battlane3, battlex, dodgeman

### PR DESCRIPTION
**Pull request by shaunquick**
hiscore support added to multiple games (other issues with games such as sound have not been updated)

### CODE REVIEW

**Comment by shaunquick** [comment]
added hiscore support for blockout, blockout2, blockout3, blockoutj, agress, agressb, bogeyman, bzone, bzonea, bzonec, redbaron, redbarona, calorie, calorieb, canyon, canyonp, cheekyms, cloak, cloaksp, cloakfr, cloakgr, cop01, cop01a, mightguy

**Comment by dinkc64** [comment]
This is great, and a super awesome help!  thanks :)
p.s. what do you mean by "(other issues with games such as sound have not been updated)"?

best regards,
- dink

**Comment by shaunquick** [comment]
Hi dink,
Before I add hiscores, I test the game out and then test after the code additions - there are occasions where the sound quality is poor both before and after (i didn't note the game) hiscore addition. Hope that clarifies.

Cheers,

shaunquick

**Comment by dinkc64** [comment]
In the future if you come across anything not up to par, please note it here :)

best regards,
- dink

**Pull request merged**
