### PR TITLE
update d_vendetta.cpp :

### PR DESCRIPTION
**Pull request by taoenwen**
sync mame : added PLDs (BAD_DUMP / Bruteforced)

### CODE REVIEW

**Comment by dinkc64** [comment]
taoenwen, ym2151 volume too low now (0.05), please check.

**Comment by taoenwen** [comment]
@dinkc64 Yes, my mistake!

image

**Comment by dinkc64** [comment]
please keep in mind: we set a lot of volumes different from mame on purpose, so please make sure it really sounds better or more balanced if you change a volume, instead of changing it just because mame did.

best regards,
- dink

**Comment by taoenwen** [comment]
I understand

**Comment by taoenwen** [comment]
@dinkc64 Thanks!

**Pull request merged**
